nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025374_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025374_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025375_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025375_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025376_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025376_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025377_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025377_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025378_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025378_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025379_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025379_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025380_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025380_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025381_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025381_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025382_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025382_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025383_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025383_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025385_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025385_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025386_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025386_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025387_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025387_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025388_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025388_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025389_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025389_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025390_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025390_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025391_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025391_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025392_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025392_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025393_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025393_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025394_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025394_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025395_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025395_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025396_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025396_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025397_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025397_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025398_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025398_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025399_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025399_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025400_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025400_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025401_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025401_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025402_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025402_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025403_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025403_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025404_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025404_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025405_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025405_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025406_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025406_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025407_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025407_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025408_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025408_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025409_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025409_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025500_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025500_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025510_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025510_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025511_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025511_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025520_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025520_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025521_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025521_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025522_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025522_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025523_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025523_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025524_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025524_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025525_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025525_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025526_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025526_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025527_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025527_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025528_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025528_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025529_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025529_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025530_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025530_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025531_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025531_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025532_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025532_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025533_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025533_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025534_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025534_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025535_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025535_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025536_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025536_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025537_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025537_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025538_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025538_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025539_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025539_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025540_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025540_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025541_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025541_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025542_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025542_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025543_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025543_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025544_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025544_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025545_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025545_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025546_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025546_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025550_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025550_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025551_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025551_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025552_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025552_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025553_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025553_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025554_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025554_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025555_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025555_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025556_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025556_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025557_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025557_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025558_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025558_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025559_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025559_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025560_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025560_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025571_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025571_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025572_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025572_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025573_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025573_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025574_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025574_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025575_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025575_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025576_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025576_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025577_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025577_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025578_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025578_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025579_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025579_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025580_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025580_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025581_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025581_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025582_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025582_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025583_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025583_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025584_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025584_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025585_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025585_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025586_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025586_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025587_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025587_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025588_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025588_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025589_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025589_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025590_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025590_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025591_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025591_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025592_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025592_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025593_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025593_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025594_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025594_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025595_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025595_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025596_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025596_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025597_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025597_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025598_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025598_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025599_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025599_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025600_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025600_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025601_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025601_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025602_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025602_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025603_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025603_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025604_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025604_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025605_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025605_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025606_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025606_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025607_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025607_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025608_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025608_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025609_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025609_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025610_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025610_Playlist.root >> minervame6F_Data.log

nohup xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025611_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me6F_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00025611_Playlist.root >> minervame6F_Data.log

