touch minervame1N_Data.log
xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020328_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020328_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020329_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020329_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020330_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020330_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020331_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020331_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020332_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020332_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020334_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020334_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020335_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020335_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020350_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020350_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020351_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020351_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020352_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020352_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020353_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020353_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020354_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020354_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020364_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020364_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020365_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020365_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020366_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020366_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020367_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020367_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020368_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020368_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020370_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020370_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020371_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020371_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020381_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020381_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020382_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020382_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020383_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020383_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020384_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020384_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020385_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020385_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020386_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020386_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020387_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020387_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020388_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020388_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020389_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020389_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020390_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020390_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020391_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020391_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020392_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020392_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020393_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020393_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020394_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020394_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020395_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020395_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020396_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020396_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020397_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020397_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020398_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020398_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020399_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020399_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020400_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020400_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020401_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020401_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020404_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020404_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020405_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020405_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020407_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020407_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020408_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020408_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020409_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020409_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020410_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020410_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020411_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020411_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020412_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020412_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020413_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020413_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020414_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020414_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020441_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020441_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020442_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020442_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020443_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020443_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020444_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020444_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020445_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020445_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020446_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020446_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020447_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020447_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020448_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020448_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020449_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020449_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020450_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020450_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020451_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020451_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020452_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020452_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020453_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020453_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020454_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020454_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020455_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020455_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020457_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020457_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020458_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020458_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020459_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020459_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020460_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020460_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020461_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020461_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020462_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020462_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020463_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020463_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020464_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020464_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020465_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020465_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020466_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020466_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020467_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020467_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020468_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020468_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020469_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020469_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020470_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020470_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020471_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020471_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020472_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020472_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020473_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020473_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020474_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020474_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020475_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020475_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020476_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020476_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020477_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020477_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020478_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020478_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020479_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020479_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020480_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020480_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020481_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020481_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020482_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020482_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020483_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020483_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020484_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020484_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020485_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020485_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020486_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020486_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020487_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020487_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020488_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020488_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020489_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020489_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020490_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020490_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020491_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020491_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020492_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020492_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020493_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020493_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020494_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020494_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020495_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020495_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020496_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020496_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020497_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020497_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020498_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020498_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020499_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020499_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020500_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020500_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020501_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020501_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020502_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020502_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020503_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020503_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020504_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020504_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020505_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020505_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020506_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020506_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020507_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020507_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020508_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020508_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020509_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020509_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020510_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020510_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020511_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020511_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020512_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020512_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020513_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020513_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020514_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020514_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020602_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020602_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020603_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020603_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020604_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020604_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020605_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020605_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020606_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020606_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020607_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020607_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020608_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020608_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020609_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020609_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020610_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020610_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020611_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020611_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020612_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020612_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020613_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020613_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020616_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020616_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020617_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020617_Playlist.root

xrdcopy root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/minerva/persistent/DataPreservation/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020618_Playlist.root /minerva/data/ME/p6/p6PrimeData/Merged_data_ana_me1N_DualVertex_P6Prime13FebDSECalFix/MasterAnaDev_data_AnaTuple_run00020618_Playlist.root

