---
title: "BDTG Explore"
author: "Sean Gilligan"
output: pdf_document
---

```{r, message = F, warning = F, echo = F}
library(dplyr)
library(ggplot2)
library(tidyr)
library(stringr)
library(knitr)
library(kableExtra)
library(GGally)
library(viridis)
library(fitdistrplus)
library(purrr)
library(ggforce)
#library(ggpattern)
library(xgboost)
library(caret)
library(Ckmeans.1d.dp)
library(archdata)
library(jcolors)
library(ggpp)
library(MASS)
#library(tidymodels)
```

```{r, message = F, warning = F, echo = F}
events <- read.csv("../CSV_minervame1N_p4_MC.csv", sep=";")
```

```{r, message = F, warning = F, echo = F}
colnames(events)[which(colnames(events) == "X1chargedpionBDTG")] <- "1chargedpionBDTG"
colnames(events)[which(colnames(events) == "X1neutralpionBDTG")] <- "1neutralpionBDTG"

events$Truth = gsub("Mult1p___", "", events$Truth)

events <- events %>% mutate(tracks = case_when((NumberOfProtonCandidates == 0) ~ "1track",
                                               (PrimaryProtonScore1 >= 0 & NumberOfProtonCandidates == 1) ~ "2track",
                                               (PrimaryProtonScore1 >= 0 & NumberOfProtonCandidates >= 2) ~ "3ptrack",
                                                .default = "other"))

cbind(colnames(events))
```
```{r}
isproton <- function(Q2QE,score) {
  if((Q2QE<=0.2 & score >= 0.2) || (Q2QE > 0.2 & Q2QE <= 0.6 & score >= 0.1) || Q2QE > 0.6 || score < 0){
    return(TRUE)
  }
  else {
    return(FALSE)
  }
}


```

```{r}
events <- events %>% 
  mutate(bdtg_band = case_when(qelikeBDTG <= 0.2 ~ "[0.0,0.2]",
                               qelikeBDTG <= 0.4 ~ "(0.2,0.4]",
                               qelikeBDTG <= 0.6 ~ "(0.4,0.6]",
                               qelikeBDTG <= 0.8 ~ "(0.6,0.8]",
                               qelikeBDTG <= 1.0 ~ "(0.8,1.0]"))
events$bdtg_band <- factor(events$bdtg_band, levels = c("[0.0,0.2]","(0.2,0.4]","(0.4,0.6]","(0.6,0.8]","(0.8,1.0]"))

events <- events %>% 
  mutate(bdtg_split = case_when(qelikeBDTG <= 0.5 ~ "[0.0,0.5]",
                                qelikeBDTG > 0.5 ~ "(0.5,1.0]"))
events$bdtg_split <- factor(events$bdtg_split, levels = c("[0.0,0.5]","(0.5,1.0]"))

events <- events %>%
  rowwise() %>%
  mutate(IsProton = isproton(Q2QE,PrimaryProtonScore1))

events <- events %>% 
  mutate(Sideband = case_when(IsProton == TRUE & BlobCount <= 1 & ImprovedMichelCount == 0 ~ "QELike",
                              BlobCount <= 1 & ImprovedMichelCount > 0 ~ "Michel",
                              BlobCount > 1 & ImprovedMichelCount == 0 ~ "Blob",
                              BlobCount > 1 & ImprovedMichelCount > 0 ~ "MicBlob",
                              TRUE ~ "Other"))

events$Sideband <- factor(events$Sideband, levels = c("QELike","Michel","Blob","MicBlob","Other"))

events %>% count(Sideband)
events %>% count(Truth)

events$Truth <- factor(events$Truth, levels = rev(c("qelike","1chargedpion","1neutralpion","multipion","other")))
truth_colors = rev(c("#0085ad","#af272f","#4c8c2b","#eaaa00","#522506"))
```

```{r}
nrow(events %>% filter(Q2QE <= 4) %>% 
  filter(Q2QE >= 0.01) %>%
  filter(multipionBDTG < 0.2) %>%
    filter(Truth=="qelike") %>%
  filter(qelikeBDTG > 0.5) %>%
  filter(tracks=="2track"))/nrow(events %>% filter(Q2QE <= 4) %>% 
  filter(Q2QE >= 0.01) %>%
    filter(Truth=="qelike") %>%
  filter(multipionBDTG < 0.2)  %>%
  filter(tracks=="2track"))
```
```{r, fig.height=6, fig.width=12}
ggplot(events %>% 
         filter(Q2QE <= 4) %>% 
         filter(Q2QE >= 0.01) %>%
         filter(tracks=="2track"), 
       aes(Q2QE,fill=Truth)) +
  stat_bin(breaks=c(0.01,0.03,0.05,0.1,0.2,0.4,0.6,0.8,1,1.2,2,3,4)) + theme_bw() +
  scale_x_log10(expand = c(0,0),
                n.breaks = 5) +
  scale_y_continuous(expand = expansion(mult = c(0,.1))) +
  scale_fill_manual(values = truth_colors) +
  ggtitle("QELike BDTG Response bands") +
  facet_wrap(vars(bdtg_split), scales = "free")
#ggsave("qelikeBDTG_bands_vs_Q2QE_2track_freescale.png")
```

```{r, fig.height=6, fig.width=12}
multipion_cut <- 0.5
np_cut = 0.15
qe_cut = 0.4

events <- events %>% 
  mutate(bdtg_sides = case_when(qelikeBDTG <= qe_cut & multipionBDTG > multipion_cut ~ "qelike [0.0,qe_cut] multipion (cut,1]",
                                qelikeBDTG <= qe_cut & multipionBDTG <= multipion_cut ~ "qelike [0.0,qe_cut] multipion [0.0,cut]",
                                qelikeBDTG > qe_cut ~ "(qe_cut,1.0]"))



events <- events %>% 
  mutate(bdtg_sides = case_when(qelikeBDTG <= qe_cut & multipionBDTG > multipion_cut ~ "qelike [0.0,0.5] multipion (cut,1]",
                                qelikeBDTG <= qe_cut & multipionBDTG <= multipion_cut ~ "qelike [0.0,0.5] multipion [0.0,cut]",
                                qelikeBDTG > qe_cut ~ "(0.5,1.0]"))

events$bdtg_sides <- factor(events$bdtg_sides, levels = c("(0.5,1.0]",
                                                          "qelike [0.0,0.5] multipion [0.0,cut]",
                                                          "qelike [0.0,0.5] multipion (cut,1]"))

events <- events %>% 
  mutate(bdtg_sides = case_when(qelikeBDTG <= qe_cut & multipionBDTG > multipion_cut ~ "qelike [0.0,qe_cut] multipion (cut,1]",
                                qelikeBDTG <= qe_cut & multipionBDTG <= multipion_cut & `1neutralpionBDTG` <= np_cut ~ "qelike [0.0,qe_cut] multipion [0.0,cut] 1neutralpion [0.0,np_cut]",
                                qelikeBDTG <= qe_cut & multipionBDTG <= multipion_cut & `1neutralpionBDTG` > np_cut ~ "qelike [0.0,qe_cut] multipion [0.0,cut] 1neutralpion (np_cut,1.0]",
                                qelikeBDTG > qe_cut ~ "(qe_cut,1.0]"))

events$bdtg_sides <- factor(events$bdtg_sides, levels = c("(qe_cut,1.0]",
                                                          "qelike [0.0,qe_cut] multipion [0.0,cut] 1neutralpion [0.0,np_cut]",
                                                          "qelike [0.0,qe_cut] multipion [0.0,cut] 1neutralpion (np_cut,1.0]",
                                                          "qelike [0.0,qe_cut] multipion (cut,1]"))

ggplot(events %>% 
         filter(Q2QE <= 4) %>% 
         filter(Q2QE >= 0.01) %>%
         filter(tracks=="2track"), 
       aes(Q2QE,fill=Truth)) +
  stat_bin(breaks=c(0.01,0.03,0.05,0.1,0.2,0.4,0.6,0.8,1,1.2,2,3,4)) + theme_bw() +
  scale_x_log10(expand = c(0,0)) +
  scale_y_continuous(expand = expansion(mult = c(0,.1))) +
  scale_fill_manual(values = truth_colors) +
  facet_wrap(vars(bdtg_sides), scales = "free")
#ggsave("qelikeBDTG_bands_vs_Q2QE_2track.png")
ggplot(events %>% 
         filter(Q2QE <= 4) %>% 
         filter(Q2QE >= 0.01) %>%
         filter(Sideband != "Other") %>%
         filter(tracks=="2track"), 
       aes(Q2QE,fill=Truth)) +
  stat_bin(breaks=c(0.01,0.03,0.05,0.1,0.2,0.4,0.6,0.8,1,1.2,2,3,4)) + theme_bw() +
  scale_x_log10(expand = c(0,0)) +
  scale_y_continuous(expand = expansion(mult = c(0,.1))) +
  scale_fill_manual(values = truth_colors) +
  facet_wrap(vars(Sideband), scales = "free")

ggplot(events %>% 
         filter(Q2QE <= 4) %>% 
         filter(Q2QE >= 0.01) %>%
         filter(tracks=="2track"), 
       aes(Q2QE,fill=Truth)) +
  stat_bin(breaks=c(0.01,0.03,0.05,0.1,0.2,0.4,0.6,0.8,1,1.2,2,3,4)) + theme_bw() +
  scale_x_log10(expand = c(0,0)) +
  scale_y_continuous(expand = expansion(mult = c(0,.1))) +
  scale_fill_manual(values = truth_colors) +
  facet_wrap(vars(bdtg_sides))
#ggsave("qelikeBDTG_bands_vs_Q2QE_2track.png")
ggplot(events %>% 
         filter(Q2QE <= 4) %>% 
         filter(Q2QE >= 0.01) %>%
         filter(Sideband != "Other") %>%
         filter(tracks=="2track"), 
       aes(Q2QE,fill=Truth)) +
  stat_bin(breaks=c(0.01,0.03,0.05,0.1,0.2,0.4,0.6,0.8,1,1.2,2,3,4)) + theme_bw() +
  scale_x_log10(expand = c(0,0)) +
  scale_y_continuous(expand = expansion(mult = c(0,.1))) +
  scale_fill_manual(values = truth_colors) +
  facet_wrap(vars(Sideband))


ggplot(events %>% 
         filter(Q2QE <= 4) %>% 
         filter(Q2QE >= 0.01) %>%
         filter(tracks=="2track"), 
       aes(`1chargedpionBDTG`,fill=Truth)) +
  stat_bin(breaks=seq(0,1,0.1)) + theme_bw() +
  scale_x_continuous(expand = c(0,0)) +
  scale_y_continuous(expand = expansion(mult = c(0,.1))) +
  scale_fill_manual(values = truth_colors) +
  facet_wrap(vars(bdtg_sides))

ggplot(events %>% 
         filter(Q2QE <= 4) %>% 
         filter(Q2QE >= 0.01) %>%
         filter(tracks=="2track"), 
       aes(`1neutralpionBDTG`,fill=Truth)) +
  stat_bin(breaks=seq(0,1,0.1)) + theme_bw() +
  scale_x_continuous(expand = c(0,0)) +
  scale_y_continuous(expand = expansion(mult = c(0,.1))) +
  scale_fill_manual(values = truth_colors) +
  facet_wrap(vars(bdtg_sides))

ggplot(events %>% 
         filter(Q2QE <= 4) %>% 
         filter(Q2QE >= 0.01) %>%
         filter(bdtg_sides =="qelike [0.0,0.5] multipion [0.0,cut]") %>%
         filter(tracks=="2track"), 
       aes(x=`1chargedpionBDTG`,y=`1neutralpionBDTG`)) +
  stat_bin2d() + theme_bw() +
  scale_x_continuous(expand = c(0,0)) +
  scale_y_continuous(expand = expansion(mult = c(0,.1))) +
  facet_wrap(vars(Truth))
```

```{r, fig.height=6, fig.width=12}
ggplot(events %>% 
         filter(Q2QE <= 4) %>% 
         filter(Q2QE >= 0.01) %>%
         filter(multipionBDTG < 0.2) %>%
         filter(tracks=="2track"), 
       aes(Q2QE,fill=Truth)) +
  stat_bin(breaks=c(0.01,0.03,0.05,0.1,0.2,0.4,0.6,0.8,1,1.2,2,3,4)) + theme_bw() +
  scale_x_log10(expand = c(0,0),
                n.breaks = 5) +
  scale_y_continuous(expand = expansion(mult = c(0,.1))) +
  scale_fill_manual(values = truth_colors) +
  ggtitle("QELike BDTG Response bands") +
  facet_wrap(vars(bdtg_band), scales = "free")
ggsave("qelikeBDTG_bands_vs_Q2QE_2track_freescale.png")

ggplot(events %>% 
         filter(Q2QE <= 4) %>% 
         filter(Q2QE >= 0.01) %>%
         filter(multipionBDTG < 0.2) %>%
         filter(tracks=="2track"), 
       aes(Q2QE,fill=Truth)) +
  stat_bin(breaks=c(0.01,0.03,0.05,0.1,0.2,0.4,0.6,0.8,1,1.2,2,3,4)) + theme_bw() +
  scale_x_log10(expand = c(0,0)) +
  scale_y_continuous(expand = expansion(mult = c(0,.1))) +
  scale_fill_manual(values = truth_colors) +
  ggtitle("QELike BDTG Response bands") +
  facet_wrap(vars(bdtg_band))
ggsave("qelikeBDTG_bands_vs_Q2QE_2track.png")
```
```{r, fig.height=4, fig.width=7}
ggplot(events %>% 
         filter(Q2QE <= 4) %>% 
         filter(Q2QE >= 0.01) %>%
         filter(multipionBDTG < 0.2) %>%
         filter(tracks=="2track"), 
       aes(Q2QE,fill=Truth)) +
  stat_bin(breaks=c(0.01,0.03,0.05,0.1,0.2,0.4,0.6,0.8,1,1.2,2,3,4)) + theme_bw() +
  scale_x_log10(expand = c(0,0)) +
  scale_y_continuous(limits=c(0,10000),expand = expansion(mult = c(0,.1))) +
  scale_fill_manual(values = truth_colors) +
  ggtitle("2track - No Cut")
ggplot(events %>% 
         filter(Q2QE <= 4) %>% 
         filter(Q2QE >= 0.01) %>%
         filter(multipionBDTG < 0.2) %>%
         filter(qelikeBDTG > 0.1) %>%
         filter(tracks=="2track"), 
       aes(Q2QE,fill=Truth)) +
  stat_bin(breaks=c(0.01,0.03,0.05,0.1,0.2,0.4,0.6,0.8,1,1.2,2,3,4)) + theme_bw() +
  scale_x_log10(expand = c(0,0)) +
  scale_y_continuous(limits=c(0,10000),expand = expansion(mult = c(0,.1)))+
  scale_fill_manual(values = truth_colors) +
  ggtitle("2track - QELike BDT Response > 0.1")
ggplot(events %>% 
         filter(Q2QE <= 4) %>% 
         filter(Q2QE >= 0.01) %>%
         filter(multipionBDTG < 0.2) %>%
         filter(qelikeBDTG > 0.2) %>%
         filter(tracks=="2track"), 
       aes(Q2QE,fill=Truth)) +
  stat_bin(breaks=c(0.01,0.03,0.05,0.1,0.2,0.4,0.6,0.8,1,1.2,2,3,4)) + theme_bw() +
  scale_x_log10(expand = c(0,0)) +
  scale_y_continuous(limits=c(0,10000),expand = expansion(mult = c(0,.1)))+
  scale_fill_manual(values = truth_colors) +
  ggtitle("2track - QELike BDT Response > 0.2")
ggplot(events %>% 
         filter(Q2QE <= 4) %>% 
         filter(Q2QE >= 0.01) %>%
         filter(multipionBDTG < 0.2) %>%
         filter(qelikeBDTG > 0.3) %>%
         filter(tracks=="2track"), 
       aes(Q2QE,fill=Truth)) +
  stat_bin(breaks=c(0.01,0.03,0.05,0.1,0.2,0.4,0.6,0.8,1,1.2,2,3,4)) + theme_bw() +
  scale_x_log10(expand = c(0,0)) +
  scale_y_continuous(limits=c(0,10000),expand = expansion(mult = c(0,.1)))+
  scale_fill_manual(values = truth_colors) +
  ggtitle("2track - QELike BDT Response > 0.3")
ggplot(events %>% 
         filter(Q2QE <= 4) %>% 
         filter(Q2QE >= 0.01) %>%
         filter(multipionBDTG < 0.2) %>%
         filter(qelikeBDTG > 0.4) %>%
         filter(tracks=="2track"), 
       aes(Q2QE,fill=Truth)) +
  stat_bin(breaks=c(0.01,0.03,0.05,0.1,0.2,0.4,0.6,0.8,1,1.2,2,3,4)) + theme_bw() +
  scale_x_log10(expand = c(0,0)) +
  scale_y_continuous(limits=c(0,10000),expand = expansion(mult = c(0,.1)))+
  scale_fill_manual(values = truth_colors) +
  ggtitle("2track - QELike BDT Response > 0.4")
ggplot(events %>% 
         filter(Q2QE <= 4) %>% 
         filter(Q2QE >= 0.01) %>%
         filter(multipionBDTG < 0.2) %>%
         filter(qelikeBDTG > 0.5) %>%
         filter(tracks=="2track"), 
       aes(Q2QE,fill=Truth)) +
  stat_bin(breaks=c(0.01,0.03,0.05,0.1,0.2,0.4,0.6,0.8,1,1.2,2,3,4)) + theme_bw() +
  scale_x_log10(expand = c(0,0)) +
  scale_y_continuous(limits=c(0,10000),expand = expansion(mult = c(0,.1)))+
  scale_fill_manual(values = truth_colors) +
  ggtitle("2track - QELike BDT Response > 0.5")
ggplot(events %>% 
         filter(Q2QE <= 4) %>% 
         filter(Q2QE >= 0.01) %>%
         filter(multipionBDTG < 0.2) %>%
         filter(qelikeBDTG > 0.6) %>%
         filter(tracks=="2track"), 
       aes(Q2QE,fill=Truth)) +
  stat_bin(breaks=c(0.01,0.03,0.05,0.1,0.2,0.4,0.6,0.8,1,1.2,2,3,4)) + theme_bw() +
  scale_x_log10(expand = c(0,0)) +
  scale_y_continuous(limits=c(0,10000),expand = expansion(mult = c(0,.1)))+
  scale_fill_manual(values = truth_colors) +
  ggtitle("2track - QELike BDT Response > 0.6")
ggplot(events %>% 
         filter(Q2QE <= 4) %>% 
         filter(Q2QE >= 0.01) %>%
         filter(multipionBDTG < 0.2) %>%
         filter(qelikeBDTG > 0.7) %>%
         filter(tracks=="2track"), 
       aes(Q2QE,fill=Truth)) +
  stat_bin(breaks=c(0.01,0.03,0.05,0.1,0.2,0.4,0.6,0.8,1,1.2,2,3,4)) + theme_bw() +
  scale_x_log10(expand = c(0,0)) +
  scale_y_continuous(limits=c(0,10000),expand = expansion(mult = c(0,.1)))+
  scale_fill_manual(values = truth_colors) +
  ggtitle("2track - QELike BDT Response > 0.7")
ggplot(events %>% 
         filter(Q2QE <= 4) %>% 
         filter(Q2QE >= 0.01) %>%
         filter(multipionBDTG < 0.2) %>%
         filter(qelikeBDTG > 0.8) %>%
         filter(tracks=="2track"), 
       aes(Q2QE,fill=Truth)) +
  stat_bin(breaks=c(0.01,0.03,0.05,0.1,0.2,0.4,0.6,0.8,1,1.2,2,3,4)) + theme_bw() +
  scale_x_log10(expand = c(0,0)) +
  scale_y_continuous(limits=c(0,10000),expand = expansion(mult = c(0,.1)))+
  scale_fill_manual(values = truth_colors) +
  ggtitle("2track - QELike BDT Response > 0.8")
ggplot(events %>% 
         filter(Q2QE <= 4) %>% 
         filter(Q2QE >= 0.01) %>%
         filter(multipionBDTG < 0.2) %>%
         filter(qelikeBDTG > 0.9) %>%
         filter(tracks=="2track"), 
       aes(Q2QE,fill=Truth)) +
  stat_bin(breaks=c(0.01,0.03,0.05,0.1,0.2,0.4,0.6,0.8,1,1.2,2,3,4)) + theme_bw() +
  scale_x_log10(expand = c(0,0)) +
  scale_y_continuous(limits=c(0,10000),expand = expansion(mult = c(0,.1)))+
  scale_fill_manual(values = truth_colors[2:5]) +
  ggtitle("2track - QELike BDT Response > 0.9")
```
```{r, fig.height=4, fig.width=7}
ggplot(events %>% 
         filter(Q2QE <= 4) %>% 
         filter(Q2QE >= 0.01) %>%
         filter(multipionBDTG < 0.2) %>%
         filter(tracks=="2track"), 
       aes(Q2QE,fill=Truth)) +
  stat_bin(breaks=c(0.01,0.03,0.05,0.1,0.2,0.4,0.6,0.8,1,1.2,2,3,4)) + theme_bw() +
  scale_x_log10(expand = c(0,0)) +
  scale_y_continuous(expand = expansion(mult = c(0,.1))) +
  scale_fill_manual(values = truth_colors) +
  ggtitle("2track - No Cut")
ggplot(events %>% 
         filter(Q2QE <= 4) %>% 
         filter(Q2QE >= 0.01) %>%
         filter(multipionBDTG < 0.2) %>%
         filter(qelikeBDTG > 0.1) %>%
         filter(tracks=="2track"), 
       aes(Q2QE,fill=Truth)) +
  stat_bin(breaks=c(0.01,0.03,0.05,0.1,0.2,0.4,0.6,0.8,1,1.2,2,3,4)) + theme_bw() +
  scale_x_log10(expand = c(0,0)) +
  scale_y_continuous(expand = expansion(mult = c(0,.1)))+
  scale_fill_manual(values = truth_colors) +
  ggtitle("2track - QELike BDT Response > 0.1")
ggplot(events %>% 
         filter(Q2QE <= 4) %>% 
         filter(Q2QE >= 0.01) %>%
         filter(multipionBDTG < 0.2) %>%
         filter(qelikeBDTG > 0.2) %>%
         filter(tracks=="2track"), 
       aes(Q2QE,fill=Truth)) +
  stat_bin(breaks=c(0.01,0.03,0.05,0.1,0.2,0.4,0.6,0.8,1,1.2,2,3,4)) + theme_bw() +
  scale_x_log10(expand = c(0,0)) +
  scale_y_continuous(expand = expansion(mult = c(0,.1)))+
  scale_fill_manual(values = truth_colors) +
  ggtitle("2track - QELike BDT Response > 0.2")
ggplot(events %>% 
         filter(Q2QE <= 4) %>% 
         filter(Q2QE >= 0.01) %>%
         filter(multipionBDTG < 0.2) %>%
         filter(qelikeBDTG > 0.3) %>%
         filter(tracks=="2track"), 
       aes(Q2QE,fill=Truth)) +
  stat_bin(breaks=c(0.01,0.03,0.05,0.1,0.2,0.4,0.6,0.8,1,1.2,2,3,4)) + theme_bw() +
  scale_x_log10(expand = c(0,0)) +
  scale_y_continuous(expand = expansion(mult = c(0,.1)))+
  scale_fill_manual(values = truth_colors) +
  ggtitle("2track - QELike BDT Response > 0.3")
ggplot(events %>% 
         filter(Q2QE <= 4) %>% 
         filter(Q2QE >= 0.01) %>%
         filter(multipionBDTG < 0.2) %>%
         filter(qelikeBDTG > 0.4) %>%
         filter(tracks=="2track"), 
       aes(Q2QE,fill=Truth)) +
  stat_bin(breaks=c(0.01,0.03,0.05,0.1,0.2,0.4,0.6,0.8,1,1.2,2,3,4)) + theme_bw() +
  scale_x_log10(expand = c(0,0)) +
  scale_y_continuous(expand = expansion(mult = c(0,.1)))+
  scale_fill_manual(values = truth_colors) +
  ggtitle("2track - QELike BDT Response > 0.4")
ggplot(events %>% 
         filter(Q2QE <= 4) %>% 
         filter(Q2QE >= 0.01) %>%
         filter(multipionBDTG < 0.2) %>%
         filter(qelikeBDTG > 0.5) %>%
         filter(tracks=="2track"), 
       aes(Q2QE,fill=Truth)) +
  stat_bin(breaks=c(0.01,0.03,0.05,0.1,0.2,0.4,0.6,0.8,1,1.2,2,3,4)) + theme_bw() +
  scale_x_log10(expand = c(0,0)) +
  scale_y_continuous(expand = expansion(mult = c(0,.1)))+
  scale_fill_manual(values = truth_colors) +
  ggtitle("2track - QELike BDT Response > 0.5")
ggplot(events %>% 
         filter(Q2QE <= 4) %>% 
         filter(Q2QE >= 0.01) %>%
         filter(multipionBDTG < 0.2) %>%
         filter(qelikeBDTG > 0.6) %>%
         filter(tracks=="2track"), 
       aes(Q2QE,fill=Truth)) +
  stat_bin(breaks=c(0.01,0.03,0.05,0.1,0.2,0.4,0.6,0.8,1,1.2,2,3,4)) + theme_bw() +
  scale_x_log10(expand = c(0,0)) +
  scale_y_continuous(expand = expansion(mult = c(0,.1)))+
  scale_fill_manual(values = truth_colors) +
  ggtitle("2track - QELike BDT Response > 0.6")
ggplot(events %>% 
         filter(Q2QE <= 4) %>% 
         filter(Q2QE >= 0.01) %>%
         filter(multipionBDTG < 0.2) %>%
         filter(qelikeBDTG > 0.7) %>%
         filter(tracks=="2track"), 
       aes(Q2QE,fill=Truth)) +
  stat_bin(breaks=c(0.01,0.03,0.05,0.1,0.2,0.4,0.6,0.8,1,1.2,2,3,4)) + theme_bw() +
  scale_x_log10(expand = c(0,0)) +
  scale_y_continuous(expand = expansion(mult = c(0,.1)))+
  scale_fill_manual(values = truth_colors) +
  ggtitle("2track - QELike BDT Response > 0.7")
ggplot(events %>% 
         filter(Q2QE <= 4) %>% 
         filter(Q2QE >= 0.01) %>%
         filter(multipionBDTG < 0.2) %>%
         filter(qelikeBDTG > 0.8) %>%
         filter(tracks=="2track"), 
       aes(Q2QE,fill=Truth)) +
  stat_bin(breaks=c(0.01,0.03,0.05,0.1,0.2,0.4,0.6,0.8,1,1.2,2,3,4)) + theme_bw() +
  scale_x_log10(expand = c(0,0)) +
  scale_y_continuous(expand = expansion(mult = c(0,.1)))+
  scale_fill_manual(values = truth_colors) +
  ggtitle("2track - QELike BDT Response > 0.8")
ggplot(events %>% 
         filter(Q2QE <= 4) %>% 
         filter(Q2QE >= 0.01) %>%
         filter(multipionBDTG < 0.2) %>%
         filter(qelikeBDTG > 0.9) %>%
         filter(tracks=="2track"), 
       aes(Q2QE,fill=Truth)) +
  stat_bin(breaks=c(0.01,0.03,0.05,0.1,0.2,0.4,0.6,0.8,1,1.2,2,3,4)) + theme_bw() +
  scale_x_log10(expand = c(0,0)) +
  scale_y_continuous(expand = expansion(mult = c(0,.1)))+
  scale_fill_manual(values = truth_colors[2:5]) +
  ggtitle("2track - QELike BDT Response > 0.9")
```

```{r}
events %>%
  filter(qelikeBDTG < 0.4) %>%
  filter(qelikeBDTG >= 0.1) %>%
  ggplot(mapping = aes(x=PrimaryProtonScore1,fill=Truth)) +
    stat_bin(bins = 20) + theme_bw() +
    ggtitle("0.1 <= qelikeBDTG < 0.4") +
    scale_x_continuous(expand = c(0,0)) +
    scale_y_continuous(expand = expansion(mult = c(0,.1)))

events %>%
  filter(qelikeBDTG < 0.4) %>%
  filter(qelikeBDTG >= 0.1) %>%
  ggplot(aes(x=PrimaryProtonScore1,fill=Truth)) +
    geom_histogram(position="fill",bins = 20) + 
    ggtitle("0.1 <= qelikeBDTG < 0.4") +
    theme_bw() +
    scale_x_continuous(expand = c(0,0)) +
    scale_y_continuous(expand = c(0,0))
```

```{r}
events %>%
  filter(qelikeBDTG < 0.4) %>%
  filter(qelikeBDTG >= 0.1) %>%
  filter(PrimaryProtonTrackVtxGap <= 300) %>%
  ggplot(mapping = aes(x=PrimaryProtonTrackVtxGap,fill=Truth)) +
    stat_bin(bins = 20) + theme_bw() +
    scale_x_continuous(expand = c(0,0)) +
    scale_y_continuous(expand = expansion(mult = c(0,.1)))

events %>%
  filter(qelikeBDTG < 0.4) %>%
  filter(qelikeBDTG >= 0.1) %>%
  filter(PrimaryProtonTrackVtxGap <= 300) %>%
  ggplot(aes(x=PrimaryProtonTrackVtxGap,fill=Truth)) +
    geom_histogram(position="fill",bins = 20) + 
    theme_bw() +
    scale_x_continuous(expand = c(0,0)) +
    scale_y_continuous(expand = c(0,0))
```
```{r}
events %>%
  filter(Q2QE < 0.03) %>%
  filter(Q2QE > 0.0) %>%
  ggplot(mapping = aes(x=Q2QE,fill=Truth)) +
    stat_bin(bins = 20) + theme_bw() +
    scale_y_continuous(expand = expansion(mult = c(0,.1))) +
    scale_x_log10()
    scale_x_continuous(expand = c(0,0))
```
```{r}
events %>%
  filter(qelikeBDTG < 0.4) %>%
  filter(qelikeBDTG >= 0.1) %>%
  filter(Truth == "qelike") %>% 
  pull(Arachne)
```

```{r}
events <- events$Q2QE
sum(events > 4)/length(events)
quantile(events[which(events<4)], probs = seq(0,1,length.out = 7))

hist(events[which(events<4)], breaks = c(0,0.125,0.25,0.41,0.64,1.05,4))
hist(events[which(events<4)], breaks = c(0,0.124037,0.248861,0.407641,0.637749,1.077180,3.999720))

c(sum(events < 0.124037),
  sum(events < 0.248861) - sum(events < 0.124037),
  sum(events < 0.407641) - sum(events < 0.248861),
  sum(events < 0.637749) - sum(events < 0.407641),
  sum(events < 1.077180) - sum(events < 0.637749),
  sum(events < 3.999720) - sum(events < 1.077180))

c(sum(events < 0.125),
  sum(events < 0.25) - sum(events < 0.125),
  sum(events < 0.41) - sum(events < 0.25),
  sum(events < 0.64) - sum(events < 0.41),
  sum(events < 1.05) - sum(events < 0.64),
  sum(events < 4) - sum(events < 1.05))

c(sum(events < 0.1),
  sum(events < 0.2) - sum(events < 0.1),
  sum(events < 0.4) - sum(events < 0.2),
  sum(events < 0.6) - sum(events < 0.4),
  sum(events < 1) - sum(events < 0.6),
  sum(events < 4) - sum(events < 1))

c(sum(events < 0.2),
  sum(events < 0.4) - sum(events < 0.2),
  sum(events < 0.6) - sum(events < 0.4),
  sum(events < 1) - sum(events < 0.6),
  sum(events < 4) - sum(events < 1))
```

```{r, message = F, warning = F, echo = F}
percent <- function(x, digits = 2, format = "f", ...) {
  paste0(formatC(x * 100, format = format, digits = digits, ...), "%")
}

diffplot <- function(evts, x, xbreaks = seq(0,1,0.2), title, bin_width, units = "", wgt = 1) {
  ggplot() +
    geom_histogram(evts, position = position_stacknudge(x=bin_width),
             mapping = aes({{x}}, pattern_fill = Truth, weight = {{wgt}}*weight/bin_width),
             pattern = "magick", fill = "white", pattern_type = "hs_diagcross", pattern_scale = 0.45,
             binwidth = bin_width, center = bin_width/2) +
    stat_bin(evts, position = position_stacknudge(x=bin_width/2),
             mapping = aes({{x}}, color = Truth, weight = {{wgt}}*weight/bin_width),
             binwidth = bin_width, center = bin_width/2, geom = "step") +
    theme_bw() + ggtitle(title) + ylab(paste("events per",bin_width,units)) +
    scale_pattern_fill_manual(values = truth_colors) +
    scale_color_manual(values = truth_colors) +
    scale_x_continuous(expand = c(0,0), limits = c(min(xbreaks)-bin_width/1000,max(xbreaks)+bin_width/1000), breaks = xbreaks) +
    scale_y_continuous(expand = expansion(mult = c(0,.1)), n.breaks = 12, labels = scales::scientific)
}

propplot <- function(evts, x, xbreaks = seq(0,1,0.2), title, bin_width, units = "", wgt = 1) {
  ggplot() +
    geom_histogram(evts, position = position_fillnudge(x=bin_width),
             mapping = aes({{x}}, pattern_fill = Truth, weight = {{wgt}}*weight/bin_width),
             pattern = "magick", fill = "white", pattern_type = "hs_diagcross", pattern_scale = 0.45,
             binwidth = bin_width, origin = 0) +
    stat_bin(evts, position = position_stacknudge(x=bin_width/2),
             mapping = aes({{x}}, color = Truth, weight = {{wgt}}*weight/bin_width),
             binwidth = bin_width, boundary = 0, geom = "step") +
    theme_bw() + ggtitle(title) + ylab("relative contribution") +
    scale_pattern_fill_manual(values = truth_colors) +
    scale_color_manual(values = truth_colors) +
    scale_x_continuous(expand = c(0,0), limits = c(min(xbreaks)-bin_width/1000,max(xbreaks)+bin_width/1000), breaks = xbreaks) +
    scale_y_continuous(expand = c(0,0), limits = c(0,1), breaks = seq(0,10,0.1))
}
```

```{r, message = F, warning = F, echo = F}
events %>% group_by(Multiplicity,NumberOfProtonCandidates) %>% count()
events %>% group_by(Multiplicity) %>% count()
events %>% group_by(NumberOfProtonCandidates) %>% count()

events %>% group_by(Truth) %>% count() %>% mutate(`n%` = percent(n/nrow(events)))
events %>% filter((Multiplicity-1) > NumberOfProtonCandidates) %>% group_by(Truth) %>% count() %>%
  mutate(`n%` = percent(n/(events %>% filter((Multiplicity-1) > NumberOfProtonCandidates) %>% nrow())))
events %>% filter((Multiplicity-1) == NumberOfProtonCandidates) %>% group_by(Truth) %>% count() %>%
  mutate(`n%` = percent(n/(events %>% filter((Multiplicity-1) == NumberOfProtonCandidates) %>% nrow())))

diffplot(events %>% mutate(MissingTracks = Multiplicity-1-NumberOfProtonCandidates),MissingTracks,0:5,"Missing Tracks",1)
propplot(events %>% mutate(MissingTracks = Multiplicity-1-NumberOfProtonCandidates),MissingTracks,0:5,"Missing Tracks",1)  
  
events %>% mutate(MissingTracks = Multiplicity-1-NumberOfProtonCandidates) %>% group_by(MissingTracks) %>% count()
```

```{r, message = F, warning = F, echo = F}
ggplot(events %>% 
         filter(tracks == "1track")) +
  stat_bin(binwidth = 0.05, position = position_stacknudge(x = 0.025), mapping = aes(qelikeBDTG, fill = Truth)) +
  stat_bin(color = "black", geom = "step", binwidth = 0.05, position = position_stacknudge(x = 0), mapping = aes(qelikeBDTG, fill = Truth)) + 
  theme_bw() + ggtitle("1 Track") +
  scale_x_continuous(expand = c(0,0), limits = c(0,1)) +
  scale_y_continuous(expand = expansion(mult = c(0,0.05)))

ggplot(events %>% 
         filter(PrimaryProtonScore1 < 0) %>% 
         filter(SecProtonScore1_1 < 0)) +
  stat_bin(binwidth = 0.05, position = position_stacknudge(x = 0.025), mapping = aes(qelikeBDTG, fill = Truth)) +
  stat_bin(color = "black", geom = "step", binwidth = 0.05, position = position_stacknudge(x = 0), mapping = aes(qelikeBDTG, fill = Truth)) + 
  theme_bw() + ggtitle("1 Track") +
  scale_x_continuous(expand = c(0,0), limits = c(0,1)) +
  scale_y_continuous(expand = expansion(mult = c(0,0.05))) +
  facet_wrap(vars(Truth), scales = "free")

ggplot(events %>% 
         filter(PrimaryProtonScore1 < 0) %>%
         filter(SecProtonScore1_1 < 0))  +
  stat_bin(binwidth = 0.05, mapping = aes(qelikeBDTG, fill = Truth), position = position_fillnudge(x = 0.025)) +
  stat_bin(color = "black", geom = "step", binwidth = 0.05, position = position_fillnudge(x = 0), mapping = aes(qelikeBDTG, fill = Truth)) + 
  theme_bw() + ggtitle("1 Track") +
  scale_x_continuous(expand = c(0,0), limits = c(0,1)) +
  scale_y_continuous(expand = expansion(mult = c(0,0)))
```
```{r, message = F, warning = F, echo = F, fig.height = 5, fig.width = 10}
diffplot(events %>% filter(tracks=="1track"),  qelikeBDTG,        seq(0,1,0.2), "1track", 0.025, "")
diffplot(events %>% filter(tracks=="1track"), `1chargedpionBDTG`, seq(0,1,0.2), "1track", 0.05,  "")
diffplot(events %>% filter(tracks=="1track"), `1neutralpionBDTG`, seq(0,1,0.2), "1track", 0.05,  "")
diffplot(events %>% filter(tracks=="1track"),  multipionBDTG,     seq(0,1,0.2), "1track", 0.05,  "")
```
```{r, message = F, warning = F, echo = F}
propplot(events %>% filter(tracks=="1track"),  qelikeBDTG,        seq(0,1,0.2), "1track", 0.025, "")
propplot(events %>% filter(tracks=="1track"), `1chargedpionBDTG`, seq(0,1,0.2), "1track", 0.05,  "")
propplot(events %>% filter(tracks=="1track"), `1neutralpionBDTG`, seq(0,1,0.2), "1track", 0.05,  "")
propplot(events %>% filter(tracks=="1track"),  multipionBDTG,     seq(0,1,0.2), "1track", 0.05,  "")
```
```{r, message = F, warning = F, echo = F, fig.height = 5, fig.width = 10}
diffplot(events %>% filter(tracks=="2track"),  qelikeBDTG,        seq(0,1,0.2), "2track", 0.025, "")
diffplot(events %>% filter(tracks=="2track"), `1chargedpionBDTG`, seq(0,1,0.2), "2track", 0.05,  "")
diffplot(events %>% filter(tracks=="2track"), `1neutralpionBDTG`, seq(0,1,0.2), "2track", 0.05,  "")
diffplot(events %>% filter(tracks=="2track"),  multipionBDTG,     seq(0,1,0.2), "2track", 0.05,  "")
diffplot(events %>% filter(tracks=="2track"),  ptmu,              seq(0,2.5,0.1), "2track", 0.1, "")
diffplot(events %>% filter(tracks=="2track"),  zvtx,              c(5700,seq(6000,8500,500)), "2track", 28, "")
```
```{r, message = F, warning = F, echo = F}
propplot(events %>% filter(tracks=="2track"),  qelikeBDTG,        seq(0,1,0.2), "2track", 0.025, "")
propplot(events %>% filter(tracks=="2track"), `1chargedpionBDTG`, seq(0,1,0.2), "2track", 0.05,  "")
propplot(events %>% filter(tracks=="2track"), `1neutralpionBDTG`, seq(0,1,0.2), "2track", 0.05,  "")
propplot(events %>% filter(tracks=="2track"),  multipionBDTG,     seq(0,1,0.2), "2track", 0.05,  "")
```
```{r, message = F, warning = F, echo = F, fig.height = 5, fig.width = 10}
diffplot(events %>% filter(tracks=="2track"),  ptmu,  seq(0,2.5,0.1), "2track", 0.1, "", qelikeBDTG)
diffplot(events %>% filter(tracks=="2track"), `pzmu`, seq(0, 15,0.5), "2track", 1.0, "", qelikeBDTG)
diffplot(events %>% filter(tracks=="2track"), `Q2QE`, seq(0,  4,0.5), "2track", 0.1, "", qelikeBDTG)
```
```{r, message = F, warning = F, echo = F, fig.height = 5, fig.width = 10}
propplot(events %>% filter(tracks=="2track"),  ptmu,  seq(0,2.5,0.1), "2track", 0.1, "", qelikeBDTG)
propplot(events %>% filter(tracks=="2track"), `pzmu`, seq(0, 15,  1), "2track", 1,  "", qelikeBDTG)
propplot(events %>% filter(tracks=="2track"), `Q2QE`, seq(0,  4,0.5), "2track", 0.5,  "", qelikeBDTG)
```

```{r, message = F, warning = F, echo = F, fig.height = 5, fig.width = 10}
diffplot(events %>% filter(tracks=="3ptrack"),  qelikeBDTG,        seq(0,1,0.2), "3ptrack", 0.025, "")
diffplot(events %>% filter(tracks=="3ptrack"), `1chargedpionBDTG`, seq(0,1,0.2), "3ptrack", 0.05,  "")
diffplot(events %>% filter(tracks=="3ptrack"), `1neutralpionBDTG`, seq(0,1,0.2), "3ptrack", 0.05,  "")
diffplot(events %>% filter(tracks=="3ptrack"),  multipionBDTG,     seq(0,1,0.2), "3ptrack", 0.05,  "")
```

```{r, message = F, warning = F, echo = F}
ggplot(events %>% 
         filter(tracks == "2track")) +
  stat_bin(binwidth = 0.05, position = position_stacknudge(x = 0.025), mapping = aes(qelikeBDTG, fill = Truth)) +
  stat_bin(color = "black", geom = "step", binwidth = 0.05, position = position_stacknudge(x = 0), mapping = aes(qelikeBDTG, fill = Truth)) + 
  theme_bw() + ggtitle("2 Tracks") +
  scale_x_continuous(expand = c(0,0), limits = c(0,1)) +
  scale_y_continuous(expand = expansion(mult = c(0,0.05)))

ggplot(events %>% 
         filter(PrimaryProtonScore1 >= 0) %>% 
         filter(SecProtonScore1_1 < 0)) +
  stat_bin(binwidth = 0.05, position = position_stacknudge(x = 0.025), mapping = aes(qelikeBDTG, fill = Truth)) +
  stat_bin(color = "black", geom = "step", binwidth = 0.05, position = position_stacknudge(x = 0), mapping = aes(qelikeBDTG, fill = Truth)) + 
  theme_bw() + ggtitle("2 Tracks") +
  scale_x_continuous(expand = c(0,0), limits = c(0,1)) +
  scale_y_continuous(expand = expansion(mult = c(0,0.05))) +
  facet_wrap(vars(Truth), scales = "free")

ggplot(events %>% 
         filter(PrimaryProtonScore1 >= 0) %>%
         filter(SecProtonScore1_1 < 0))  +
  stat_bin(binwidth = 0.05, mapping = aes(qelikeBDTG, fill = Truth), position = position_fillnudge(x = 0.025)) +
  stat_bin(color = "black", geom = "step", binwidth = 0.05, position = position_fillnudge(x = 0), mapping = aes(qelikeBDTG, fill = Truth)) + 
  theme_bw() + ggtitle("2 Tracks") +
  scale_x_continuous(expand = c(0,0), limits = c(0,1)) +
  scale_y_continuous(expand = expansion(mult = c(0,0)))
```

```{r, message = F, warning = F, echo = F}
ggplot(events %>% 
         filter(PrimaryProtonScore1 >= 0) %>% 
         filter(SecProtonScore1_1 >= 0)) +
  stat_bin(binwidth = 0.05, position = position_stacknudge(x = 0.025), mapping = aes(qelikeBDTG, fill = Truth)) +
  stat_bin(color = "black", geom = "step", binwidth = 0.05, position = position_stacknudge(x = 0), mapping = aes(qelikeBDTG, fill = Truth)) + 
  theme_bw() + ggtitle("3+ Tracks") +
  scale_x_continuous(expand = c(0,0), limits = c(0,1)) +
  scale_y_continuous(expand = expansion(mult = c(0,0.05)))

ggplot(events %>% 
         filter(PrimaryProtonScore1 >= 0) %>% 
         filter(SecProtonScore1_1 >= 0)) +
  stat_bin(binwidth = 0.05, position = position_stacknudge(x = 0.025), mapping = aes(qelikeBDTG, fill = Truth)) +
  stat_bin(color = "black", geom = "step", binwidth = 0.05, position = position_stacknudge(x = 0), mapping = aes(qelikeBDTG, fill = Truth)) + 
  theme_bw() + ggtitle("3+ Tracks") +
  scale_x_continuous(expand = c(0,0), limits = c(0,1)) +
  scale_y_continuous(expand = expansion(mult = c(0,0.05))) +
  facet_wrap(vars(Truth), scales = "free")

ggplot(events %>% 
         filter(PrimaryProtonScore1 >= 0) %>%
         filter(SecProtonScore1_1 >= 0))  +
  stat_bin(binwidth = 0.05, mapping = aes(qelikeBDTG, fill = Truth), position = position_fillnudge(x = 0.025)) +
  stat_bin(color = "black", geom = "step", binwidth = 0.05, position = position_fillnudge(x = 0), mapping = aes(qelikeBDTG, fill = Truth)) + 
  theme_bw() + ggtitle("3+ Tracks") +
  scale_x_continuous(expand = c(0,0), limits = c(0,1)) +
  scale_y_continuous(expand = expansion(mult = c(0,0)))
```


```{r, message = F, warning = F, echo = F}
# 
ggplot(events %>% 
         filter(PrimaryProtonTfromdEdx >= 0) %>%
         mutate(angleDiff = PrimaryProtonAngle*360/(2*pi)-ThetamuDegrees), 
       aes(PrimaryProtonTrackVtxGap,angleDiff)) +
  stat_bin2d() +
  theme_bw() +
  scale_x_continuous(expand = c(0,0)) +
  scale_y_continuous(expand = expansion(mult = c(0,0))) +
  scale_fill_jcolors_contin("pal2")

ggplot(events %>% 
         filter(PrimaryProtonTfromdEdx >= 0) %>%
         mutate(angleDiff = PrimaryProtonAngle*360/(2*pi)-ThetamuDegrees), 
       aes(angleDiff, fill = Truth)) +
  stat_bin(color = "black") +
  theme_bw() +
  scale_x_continuous(expand = c(0,0)) +
  scale_y_continuous(expand = expansion(mult = c(0,0.05)))
ggplot(events %>% 
         filter(PrimaryProtonTfromdEdx >= 0) %>%
         mutate(angleDiff = PrimaryProtonAngle*360/(2*pi)-ThetamuDegrees)) +
  stat_bin(color = "black", mapping = aes(angleDiff, fill = Truth, y = ..count../sum(..count..)), position = "fill") +
  theme_bw() +
  scale_x_continuous(expand = c(0,0)) +
  scale_y_continuous(expand = c(0,0))

# secondary proton score 1 vs primary proton score 1
ggplot(events %>% 
         filter(PrimaryProtonTfromdEdx >= 0) %>%
         filter(SecProtonTfromdEdx_1 >= 0) %>%
         filter(qelikeBDTG >= 0.35), 
       aes(PrimaryProtonScore1, SecProtonScore1_1)) +
  stat_bin2d() +
  theme_bw() + ggtitle("qelikeBDTG >= 0.35") +
  scale_x_continuous(expand = c(0,0)) +
  scale_y_continuous(expand = expansion(mult = c(0,0))) +
  scale_fill_jcolors_contin("pal2")

ggplot(events %>% 
         filter(PrimaryProtonTfromdEdx >= 0) %>%
         filter(SecProtonTfromdEdx_1 >= 0) %>%
         filter(qelikeBDTG < 0.35), 
       aes(PrimaryProtonScore1, SecProtonScore1_1)) +
  stat_bin2d() +
  theme_bw() + ggtitle("qelikeBDTG < 0.35") +
  scale_x_continuous(expand = c(0,0)) +
  scale_y_continuous(expand = expansion(mult = c(0,0))) +
  scale_fill_jcolors_contin("pal2")

# blob count vs primary proton score 1
ggplot(events %>% 
         filter(PrimaryProtonTfromdEdx >= 0) %>%
         filter(qelikeBDTG >= 0.35), 
       aes(PrimaryProtonScore1, BlobCount)) +
  stat_bin2d(binwidth = c(0.025,1)) +
  theme_bw() + ggtitle("qelikeBDTG >= 0.35") +
  scale_x_continuous(expand = c(0,0)) +
  scale_y_continuous(expand = expansion(mult = c(0,0))) +
  scale_fill_jcolors_contin("pal2")

ggplot(events %>% 
         filter(PrimaryProtonTfromdEdx >= 0) %>%
         filter(qelikeBDTG < 0.35), 
       aes(PrimaryProtonScore1, MuonToPrimaryProtonAngle)) +
  stat_bin2d(binwidth = c(0.025,10)) +
  theme_bw() + ggtitle("qelikeBDTG < 0.35") +
  scale_x_continuous(expand = c(0,0)) +
  scale_y_continuous(expand = expansion(mult = c(0,0))) +
  scale_fill_jcolors_contin("pal2")
```


```{r, message = F, warning = F, echo = F, fig.height = 6, fig.width = 8}
ggplot(events %>% 
         mutate(qelikeBDTG_band = cut(events$qelikeBDTG, seq(0,1,0.1))) %>%
         filter(BlobCount <= 10) %>%
         filter(recoil <= 20) %>%
         filter(Multiplicity == 1), 
       aes(BlobCount, recoil)) +
  stat_bin2d(binwidth = c(1,1)) +
  theme_bw() + ggtitle("Multiplicity == 1, QELike BDT Response") +
  scale_x_continuous(expand = c(0,0)) +
  scale_y_continuous(expand = expansion(mult = c(0,0))) +
  scale_fill_jcolors_contin("pal2") +
  facet_wrap(vars(qelikeBDTG_band))

ggplot(events %>% 
         mutate(qelikeBDTG_band = cut(events$qelikeBDTG, seq(0,1,0.1))) %>%
         filter(PrimaryProtonTfromdEdx >= 0) %>%
         filter(SecProtonTfromdEdx_1 >= 0) %>%
         filter(qelikeBDTG > 0.1), 
       aes(PrimaryProtonScore1, SecProtonScore1_1)) +
  stat_bin2d(binwidth = c(0.05,0.05)) +
  theme_bw() + ggtitle("QELike BDT Response") +
  scale_x_continuous(expand = c(0,0)) +
  scale_y_continuous(expand = expansion(mult = c(0,0))) +
  scale_fill_jcolors_contin("pal2") +
  facet_wrap(vars(qelikeBDTG_band))

ggplot(events %>% 
         mutate(qelikeBDTG_band = cut(events$qelikeBDTG, seq(0,1,0.1))) %>%
         filter(PrimaryProtonTfromdEdx >= 0) %>%
         filter(BlobCount <= 20) %>%
         filter(qelikeBDTG > 0.1), 
       aes(PrimaryProtonScore1, BlobCount)) +
  stat_bin2d(binwidth = c(0.05,1)) +
  theme_bw() + ggtitle("QELike BDT Response") +
  scale_x_continuous(expand = c(0,0)) +
  scale_y_continuous(expand = expansion(mult = c(0,0))) +
  scale_fill_jcolors_contin("pal2") +
  facet_wrap(vars(qelikeBDTG_band))

ggplot(events %>% 
         mutate(qelikeBDTG_band = cut(events$qelikeBDTG, seq(0,1,0.1))) %>%
         filter(PrimaryProtonTfromdEdx >= 0) %>%
         filter(MuonToPrimaryProtonAngle > 70 | PrimaryProtonScore1 > 0.05 | MuonToPrimaryProtonAngle < 10) %>%
         filter(qelikeBDTG > 0.1),
       aes(PrimaryProtonScore1, MuonToPrimaryProtonAngle)) +
  stat_bin2d(binwidth = c(0.05,10)) +
  theme_bw() + ggtitle("QELike BDT Response") +
  scale_x_continuous(expand = c(0,0)) +
  scale_y_continuous(expand = expansion(mult = c(0,0))) +
  scale_fill_jcolors_contin("pal2") +
  facet_wrap(vars(qelikeBDTG_band))

ggplot(events %>% 
         mutate(qelikeBDTG_band = cut(events$qelikeBDTG, seq(0,1,0.1))) %>%
         filter(PrimaryProtonTfromdEdx >= 0) %>%
         filter(PrimaryProtonTrackVtxGap <= 400) %>%
         filter(PrimaryProtonTrackVtxGap > 120 | PrimaryProtonScore1 > 0.05) %>%
         filter(PrimaryProtonTrackVtxGap > 20 | PrimaryProtonScore1 > 0.25) %>%
         filter(PrimaryProtonTrackVtxGap > 60 | PrimaryProtonScore1 > 0.1) %>%
         filter(PrimaryProtonTrackVtxGap > 40 | PrimaryProtonScore1 > 0.15) %>%
         filter(qelikeBDTG > 0.1),
       aes(PrimaryProtonScore1, PrimaryProtonTrackVtxGap)) +
  stat_bin2d(binwidth = c(0.05,20)) +
  theme_bw() + ggtitle("QELike BDT Response") +
  scale_x_continuous(expand = c(0,0)) +
  scale_y_continuous(expand = expansion(mult = c(0,0))) +
  scale_fill_jcolors_contin("pal2") +
  facet_wrap(vars(qelikeBDTG_band))

```
```{r, message = F, warning = F, echo = F, fig.height = 10, fig.width = 12}
ggplot(events %>% 
         mutate(qelikeBDTG_band = cut(events$qelikeBDTG, seq(0,1,0.2))) %>%
         filter(BlobCount <= 10) %>%
         filter(recoil <= 20) %>%
         filter(Multiplicity == 1), 
       aes(BlobCount, recoil)) +
  stat_bin2d(binwidth = c(1,1)) +
  theme_bw() + ggtitle("Multiplicity == 1, QELike BDT Response") +
  scale_x_continuous(expand = c(0,0)) +
  scale_y_continuous(expand = expansion(mult = c(0,0))) +
  scale_fill_jcolors_contin("pal2") +
  facet_wrap(vars(qelikeBDTG_band, Truth), ncol = 5)

ggplot(events %>% 
         mutate(qelikeBDTG_band = cut(events$qelikeBDTG, seq(0,1,0.2))) %>%
         filter(ImprovedMichelCount <= 5) %>%
         filter(recoil <= 20) %>%
         filter(Multiplicity == 1), 
       aes(ImprovedMichelCount, recoil)) +
  stat_bin2d(binwidth = c(1,1)) +
  theme_bw() + ggtitle("Multiplicity == 1, QELike BDT Response") +
  scale_x_continuous(expand = c(0,0)) +
  scale_y_continuous(expand = expansion(mult = c(0,0))) +
  scale_fill_jcolors_contin("pal2") +
  facet_wrap(vars(qelikeBDTG_band, Truth), ncol = 5)

ggplot(events %>% 
         mutate(qelikeBDTG_band = cut(events$qelikeBDTG, seq(0,1,0.2))) %>%
         filter(ImprovedMichelCount <= 5) %>%
         filter(BlobCount <= 10) %>%
         filter(Multiplicity == 1), 
       aes(ImprovedMichelCount, BlobCount)) +
  stat_bin2d(binwidth = c(1,1)) +
  theme_bw() + ggtitle("Multiplicity == 1, QELike BDT Response") +
  scale_x_continuous(expand = c(0,0)) +
  scale_y_continuous(expand = expansion(mult = c(0,0))) +
  scale_fill_jcolors_contin("pal2") +
  facet_wrap(vars(qelikeBDTG_band, Truth), ncol = 5)
```

```{r, message = F, warning = F, echo = F}
ggplot(events %>% filter(PrimaryProtonTfromdEdx >= 0), aes(`PrimaryProtonTOF`, fill = Truth)) +
  stat_bin(origin = 0, binwidth = 200) +
  stat_bin(origin = 0, color = "black", geom = "step", binwidth = 200, position = position_stacknudge(x=-100)) + 
  theme_bw() +
  scale_x_continuous(expand = c(0,0), limits = c(0,11000)) +
  scale_y_continuous(expand = expansion(mult = c(0,0.05)))
  
ggplot(events %>% filter(PrimaryProtonTfromdEdx >= 0)) +
  stat_bin(origin = 0, binwidth = 200, mapping = aes(`PrimaryProtonTOF`, fill = Truth, y = ..count../sum(..count..)), position = "fill") +
  stat_bin(origin = 0, color = "black", geom = "step", binwidth = 200, position = position_fillnudge(x=-100), mapping = aes(`PrimaryProtonTOF`, fill = Truth, y = ..count../sum(..count..))) + 
  theme_bw() +
  scale_x_continuous(expand = c(0,0), limits = c(0,11000)) +
  scale_y_continuous(expand = expansion(mult = c(0,0)))


ggplot(events %>% filter(PrimaryProtonTfromdEdx >= 0), aes(`len/T_0`, fill = Truth)) +
  stat_bin(origin = 0, binwidth = 0.2) +
  stat_bin(origin = 0, color = "black", geom = "step", binwidth = 0.2, position = position_stacknudge(x=-0.1)) + 
  theme_bw() +
  scale_x_continuous(expand = c(0,0), limits = c(0,3.605)) +
  scale_y_continuous(expand = expansion(mult = c(0,0.05)))
  
ggplot(events %>% filter(PrimaryProtonTfromdEdx >= 0)) +
  stat_bin(origin = 0, binwidth = 0.2, mapping = aes(`len/T_0`, fill = Truth, y = ..count../sum(..count..)), position = "fill") +
  stat_bin(origin = 0, color = "black", geom = "step", binwidth = 0.2, position = position_fillnudge(x=-0.1), mapping = aes(`len/T_0`, fill = Truth, y = ..count../sum(..count..))) + 
  theme_bw() +
  scale_x_continuous(expand = c(0,0), limits = c(0,3.605)) +
  scale_y_continuous(expand = expansion(mult = c(0,0)))

ggplot(events %>% filter(PrimaryProtonTfromdEdx >= 0), aes(PrimaryProtonTfromdEdx/1000, fill = Truth)) +
  stat_bin(origin = 0, binwidth = 0.1) +
  stat_bin(origin = 0, color = "black", binwidth = 0.1, geom = "step", position = position_stacknudge(x=-0.05)) + 
  theme_bw() +
  scale_x_continuous(expand = c(0,0), limits = c(0,1.5075)) +
  scale_y_continuous(expand = expansion(mult = c(0,0.05)))
  
ggplot(events) +
  stat_bin(origin = 0, binwidth = 0.1, mapping = aes(PrimaryProtonTfromdEdx/1000, fill = Truth, y = ..count../sum(..count..)), position = "fill") +
  stat_bin(origin = 0, color = "black", geom = "step", binwidth = 0.1, position = position_fillnudge(x=-0.05), mapping = aes(PrimaryProtonTfromdEdx/1000, fill = Truth, y = ..count../sum(..count..))) + 
  theme_bw() +
  scale_x_continuous(expand = c(0,0), limits = c(0,1.5075)) +
  scale_y_continuous(expand = expansion(mult = c(0,0)))

ggplot(events %>% filter(PrimaryProtonTfromdEdx >= 0), aes(ProtonCandTrackLength_0/1000, fill = Truth)) +
  stat_bin(origin = 0, binwidth = 0.2) +
  stat_bin(origin = 0, color = "black", binwidth = 0.2, geom = "step", position = position_stacknudge(x=-0.1)) + 
  theme_bw() +
  scale_x_continuous(expand = c(0,0), limits = c(0,3.4075)) +
  scale_y_continuous(expand = expansion(mult = c(0,0.05)))
  
ggplot(events) +
  stat_bin(origin = 0, binwidth = 0.2, mapping = aes(ProtonCandTrackLength_0/1000, fill = Truth, y = ..count../sum(..count..)), position = "fill") +
  stat_bin(origin = 0, color = "black", geom = "step", binwidth = 0.2, position = position_fillnudge(x=-0.1), mapping = aes(ProtonCandTrackLength_0/1000, fill = Truth, y = ..count../sum(..count..))) + 
  theme_bw() +
  scale_x_continuous(expand = c(0,0), limits = c(0,3.4075)) +
  scale_y_continuous(expand = expansion(mult = c(0,0)))

ggplot(events %>% filter(PrimaryProtonTfromdEdx >= 0), aes(ProtonCandTrackLength_0/1000, fill = Truth, y = cumsum(..count..)/sum(..count..))) +
  stat_bin(origin = 0, binwidth = 0.2) +
  stat_bin(origin = 0, color = "black", binwidth = 0.2, geom = "step", position = position_stacknudge(x=-0.1)) + 
  theme_bw() +
  scale_x_continuous(expand = c(0,0), limits = c(0,3.4075)) +
  scale_y_continuous(expand = expansion(mult = c(0,0.05))) +
  facet_wrap(vars(Truth))

ggplot(events %>% filter(PrimaryProtonTfromdEdx >= 0), aes(x = Truth, y = `len/T_0`)) +
  geom_violin(mapping = aes(fill = Truth)) + 
  geom_boxplot(width = 0.1) +
  theme_bw()

ggplot(events %>% filter(PrimaryProtonTfromdEdx >= 0), aes(`len/T_0`, color = Truth)) +
  stat_bin(origin = 0, geom = "step", binwidth = 0.2, position = "identity") + 
  theme_bw() +
  scale_x_continuous(expand = c(0,0), limits = c(0,3.605)) +
  scale_y_continuous(expand = expansion(mult = c(0,0.05)))


events <- events %>%
  mutate(`TOF/len` = PrimaryProtonTOF/ProtonCandTrackLength_0) %>%
  mutate(`TOF/T_0` = PrimaryProtonTOF/PrimaryProtonTfromdEdx)
evt <- events %>%
  filter(PrimaryProtonTfromdEdx >= 0) %>%
  mutate(x1 = (`TOF/len`-mean(events$`TOF/len`))/sd(events$`TOF/len`)) %>%
  mutate(x2 = (`len/T_0`-mean(events$`len/T_0`))/sd(events$`len/T_0`)) %>%
  mutate(x3 = (`TOF/T_0`-mean(events$`TOF/T_0`))/sd(events$`TOF/T_0`)) %>%
  dplyr::select(x1,x2,x3,Truth)

ggpairs(evt, columns = 1:3, aes(color = Truth)) +
  theme_bw() +
  scale_x_continuous(expand = c(0,0)) +
  scale_y_continuous(expand = c(0,0))


ggplot(events %>% filter(PrimaryProtonScore1 >= 0), aes(PrimaryProtonScore1,PrimaryProtonScore2)) +
  stat_bin2d() +
  theme_bw() +
  scale_x_continuous(expand = c(0,0)) +
  scale_y_continuous(expand = c(0,0)) +
  facet_wrap(vars(Truth))

ggplot(evt, aes(x1,x3)) +
  stat_bin2d() +
  theme_bw() +
  scale_x_continuous(expand = c(0,0)) +
  scale_y_continuous(expand = c(0,0)) +
  facet_wrap(vars(Truth))

ggplot(evt, aes(x2,x3)) +
  stat_bin2d() +
  theme_bw() +
  scale_x_continuous(expand = c(0,0)) +
  scale_y_continuous(expand = c(0,0)) +
  facet_wrap(vars(Truth))

ggplot(evt, aes(x2, fill = Truth)) +
  stat_bin(origin = 0, binwidth = .2) +
  stat_bin(origin = 0, color = "black", geom = "step", binwidth = .2, position = position_stacknudge(x=-.1)) + 
  theme_bw() +
  scale_x_continuous(expand = c(0,0), limits = c(-2.4,3.4)) +
  scale_y_continuous(expand = expansion(mult = c(0,0.05)))
  
ggplot(evt) +
  stat_bin(origin = 0, binwidth = .2, mapping = aes(x2, fill = Truth, y = ..count../sum(..count..)), position = "fill") +
  stat_bin(origin = 0, color = "black", geom = "step", binwidth = .2, position = position_fillnudge(x=-.1), mapping = aes(x2, fill = Truth, y = ..count../sum(..count..))) + 
  theme_bw() +
  scale_x_continuous(expand = c(0,0), limits = c(-2.4,3.4)) +
  scale_y_continuous(expand = expansion(mult = c(0,0)))
```


```{r, message = F, warning = F, echo = F}
evt_compare <- events %>%
  group_by(Truth) %>%
  count(name = "Ntruth")
evt_compare$wgtSums <- apply(as.matrix(events[,43:47]),2,sum)[c(2:5,1)]
evt_compare <- evt_compare %>% mutate(`wgtSums/Ntruth` = signif(wgtSums/Ntruth,4))

labels <- c("qelike","1chargedpion","1neutralpion","multipion","other")
pred_n <- tibble(Pred = map_chr(1:nrow(events),~labels[which.max(events[.x,43:47])])) %>%
  group_by(Pred) %>% count()
evt_compare$maxN <- c(pred_n$n[1:3],0,pred_n$n[4])
evt_compare <- evt_compare %>% mutate(`maxN/Ntruth` = signif(maxN/Ntruth,4))

kable(evt_compare, booktabs = TRUE, escape=FALSE, align = c("lrrrrr")) %>%
  kable_styling(bootstrap_options = c("striped")) %>%
  column_spec(c(2,4), border_right = T)
```

```{r, message = F, warning = F, echo = F}
wgt_dist <- events %>% 
  group_by(Truth) %>% 
  count(wt = `1chargedpionBDTG`, name = "1chargedpion")
wgt_dist$`1neutralpion` = events %>% 
           group_by(Truth) %>% 
           count(wt = `1neutralpionBDTG`, name = "1neutralpion") %>% 
           pull(`1neutralpion`)
wgt_dist$multipion = events %>% 
           group_by(Truth) %>% 
           count(wt = multipionBDTG, name = "multipion") %>% 
           pull(multipion)
wgt_dist$other = events %>% 
           group_by(Truth) %>% 
           count(wt = otherBDTG, name = "other") %>% 
           pull(other)
wgt_dist$qelike = events %>% 
           group_by(Truth) %>% 
           count(wt = qelikeBDTG, name = "qelike") %>% 
           pull(qelike)

kable(wgt_dist, booktabs = TRUE, escape=FALSE, align = c("lrrrrr")) %>%
  kable_styling(bootstrap_options = c("striped")) %>%
  column_spec(c(1), border_right = T)

kable(cbind(wgt_dist[,1],signif(wgt_dist[,2:6]/matrix(rep(apply(as.matrix(wgt_dist[,2:6]),2,sum),5),nrow=5,byrow = T),2)), 
      booktabs = TRUE, escape=FALSE, align = c("lrrrrr")) %>%
  kable_styling(bootstrap_options = c("striped")) %>%
  column_spec(c(1), border_right = T)

```

```{r, message = F, warning = F, echo = F, fig.height = 8, fig.width = 6}
bands <- c("QELike","Michel","Blob","MicBlob")
events$Pred <- map_chr(1:nrow(events),~bands[which.max(events[.x,43:46])])
```

```{r, message = F, warning = F, echo = F, fig.height = 5, fig.width = 10}
# qelike
events %>%
  filter(model == "1track") %>%
  ggplot(aes(ptmu, fill = Truth, color = Truth, weight = qelikeBDTG*weight/0.1)) +
  stat_bin(colour = "black", binwidth = 0.1, origin = 0) +
  theme_bw() + ggtitle("qelike response weights, 1track") + ylab("events per GeV") +
  scale_x_continuous(expand = c(0,0), limits = c(0,2.5)) +
  scale_y_continuous(expand = expansion(mult = c(0, .1))) +
  facet_wrap(vars(Truth), ncol=2, scales="free_y")

events %>%
  filter(model == "1track") %>%
  ggplot(aes(ptmu, fill = Truth, color = Truth, weight = qelikeBDTG*weight/0.1)) +
  stat_bin(colour = "black", binwidth = 0.1, origin = 0) +
  theme_bw() + ggtitle("qelike response weights, 1track") + ylab("events per GeV") +
  scale_x_continuous(expand = c(0,0), limits = c(0,2.5)) +
  scale_y_continuous(expand = expansion(mult = c(0, .1))) 

events %>%
  filter(model == "1track") %>%
  ggplot(aes(ptmu, fill = Truth, color = Truth, weight = qelikeBDTG*weight/0.1)) +
  stat_bin(colour = "black", binwidth = 0.1, origin = 0, position = "fill") +
  theme_bw() + ggtitle("qelike response weights, 1track") + ylab("event contributions") +
  scale_x_continuous(expand = c(0,0), limits = c(0,2.5)) +
  scale_y_continuous(expand = expansion(mult = c(0,0)))

# 1chargedpion
events %>%
  filter(model == "1track") %>%
  ggplot(aes(ptmu, fill = Truth, color = Truth, weight = `1chargedpionBDTG`*weight/0.1)) +
  stat_bin(colour = "black", binwidth = 0.1, origin = 0) +
  theme_bw() + ggtitle("1chargedpion response weights, 1track") + ylab("events per GeV") +
  scale_x_continuous(expand = c(0,0), limits = c(0,2.5)) +
  scale_y_continuous(expand = expansion(mult = c(0, .1)))

events %>%
  filter(model == "1track") %>%
  ggplot(aes(ptmu, fill = Truth, color = Truth, weight = `1chargedpionBDTG`*weight/0.1)) +
  stat_bin(colour = "black", binwidth = 0.1, origin = 0, position = "fill") +
  theme_bw() + ggtitle("1chargedpion response weights, 1track") + ylab("event contributions") +
  scale_x_continuous(expand = c(0,0), limits = c(0,2.5)) +
  scale_y_continuous(expand = expansion(mult = c(0,0)))

# 1neutralpion
events %>%
  filter(model == "1track") %>%
  ggplot(aes(ptmu, fill = Truth, color = Truth, weight = `1neutralpionBDTG`*weight/0.1)) +
  stat_bin(colour = "black", binwidth = 0.1, origin = 0) +
  theme_bw() + ggtitle("1neutralpion response weights, 1track") + ylab("events per GeV") +
  scale_x_continuous(expand = c(0,0), limits = c(0,2.5)) +
  scale_y_continuous(expand = expansion(mult = c(0, .1)))

events %>%
  filter(model == "1track") %>%
  ggplot(aes(ptmu, fill = Truth, color = Truth, weight = `1neutralpionBDTG`*weight/0.1)) +
  stat_bin(colour = "black", binwidth = 0.1, origin = 0, position = "fill") +
  theme_bw() + ggtitle("1neutralpion response weights, 1track") + ylab("event contributions") +
  scale_x_continuous(expand = c(0,0), limits = c(0,2.5)) +
  scale_y_continuous(expand = expansion(mult = c(0,0)))

# multipion
events %>%
  filter(model == "1track") %>%
  ggplot(aes(ptmu, fill = Truth, color = Truth, weight = multipionBDTG*weight/0.1)) +
  stat_bin(colour = "black", binwidth = 0.1, origin = 0) +
  theme_bw() + ggtitle("multipion response weights, 1track") + ylab("events per GeV") +
  scale_x_continuous(expand = c(0,0), limits = c(0,2.5)) +
  scale_y_continuous(expand = expansion(mult = c(0, .1)))

events %>%
  filter(model == "1track") %>%
  ggplot(aes(ptmu, fill = Truth, color = Truth, weight = multipionBDTG*weight/0.1)) +
  stat_bin(colour = "black", binwidth = 0.1, origin = 0, position = "fill") +
  theme_bw() + ggtitle("multipion response weights") + ylab("event contributions") +
  scale_x_continuous(expand = c(0,0), limits = c(0,2.5)) +
  scale_y_continuous(expand = expansion(mult = c(0,0)))

# other
events %>%
  filter(model == "1track") %>%
  ggplot(aes(ptmu, fill = Truth, color = Truth, weight = otherBDTG*weight/0.1)) +
  stat_bin(colour = "black", binwidth = 0.1, origin = 0) +
  theme_bw() + ggtitle("other response weights, 1track") + ylab("events per GeV") +
  scale_x_continuous(expand = c(0,0), limits = c(0,2.5)) +
  scale_y_continuous(expand = expansion(mult = c(0, .1)))

events %>%
  filter(model == "1track") %>%
  ggplot(aes(ptmu, fill = Truth, color = Truth, weight = otherBDTG*weight/0.1)) +
  stat_bin(colour = "black", binwidth = 0.1, origin = 0, position = "fill") +
  theme_bw() + ggtitle("other response weights, 1track") + ylab("event contributions") +
  scale_x_continuous(expand = c(0,0), limits = c(0,2.5)) +
  scale_y_continuous(expand = expansion(mult = c(0,0)))
```

```{r, message = F, warning = F, echo = F, fig.height = 5, fig.width = 10}
# qelike
events %>%
  filter(model == "2track") %>%
  ggplot(aes(ptmu, fill = Truth, color = Truth, weight = qelikeBDTG*weight/0.1)) +
  stat_bin(colour = "black", binwidth = 0.1, origin = 0) +
  theme_bw() + ggtitle("qelike response weights, 2track") + ylab("events per GeV") +
  scale_x_continuous(expand = c(0,0), limits = c(0,2.5)) +
  scale_y_continuous(expand = expansion(mult = c(0, .1))) +
  facet_wrap(vars(Truth), ncol=2, scales="free_y")

events %>%
  filter(model == "2track") %>%
  ggplot(aes(ptmu, fill = Truth, color = Truth, weight = qelikeBDTG*weight/0.1)) +
  stat_bin(colour = "black", binwidth = 0.1, origin = 0) +
  theme_bw() + ggtitle("qelike response weights, 2track") + ylab("events per GeV") +
  scale_x_continuous(expand = c(0,0), limits = c(0,2.5)) +
  scale_y_continuous(expand = expansion(mult = c(0, .1))) 

events %>%
  filter(model == "2track") %>%
  ggplot(aes(ptmu, fill = Truth, color = Truth, weight = qelikeBDTG*weight/0.1)) +
  stat_bin(colour = "black", binwidth = 0.1, origin = 0, position = "fill") +
  theme_bw() + ggtitle("qelike response weights, 2track") + ylab("event contributions") +
  scale_x_continuous(expand = c(0,0), limits = c(0,2.5)) +
  scale_y_continuous(expand = expansion(mult = c(0,0)))

# 1chargedpion
events %>%
  filter(model == "1track") %>%
  ggplot(aes(ptmu, fill = Truth, color = Truth, weight = `1chargedpionBDTG`*weight/0.1)) +
  stat_bin(colour = "black", binwidth = 0.1, origin = 0) +
  theme_bw() + ggtitle("1chargedpion response weights, 1track") + ylab("events per GeV") +
  scale_x_continuous(expand = c(0,0), limits = c(0,2.5)) +
  scale_y_continuous(expand = expansion(mult = c(0, .1)))

events %>%
  filter(model == "1track") %>%
  ggplot(aes(ptmu, fill = Truth, color = Truth, weight = `1chargedpionBDTG`*weight/0.1)) +
  stat_bin(colour = "black", binwidth = 0.1, origin = 0, position = "fill") +
  theme_bw() + ggtitle("1chargedpion response weights, 1track") + ylab("event contributions") +
  scale_x_continuous(expand = c(0,0), limits = c(0,2.5)) +
  scale_y_continuous(expand = expansion(mult = c(0,0)))

# 1neutralpion
events %>%
  filter(model == "1track") %>%
  ggplot(aes(ptmu, fill = Truth, color = Truth, weight = `1neutralpionBDTG`*weight/0.1)) +
  stat_bin(colour = "black", binwidth = 0.1, origin = 0) +
  theme_bw() + ggtitle("1neutralpion response weights, 1track") + ylab("events per GeV") +
  scale_x_continuous(expand = c(0,0), limits = c(0,2.5)) +
  scale_y_continuous(expand = expansion(mult = c(0, .1)))

events %>%
  filter(model == "1track") %>%
  ggplot(aes(ptmu, fill = Truth, color = Truth, weight = `1neutralpionBDTG`*weight/0.1)) +
  stat_bin(colour = "black", binwidth = 0.1, origin = 0, position = "fill") +
  theme_bw() + ggtitle("1neutralpion response weights, 1track") + ylab("event contributions") +
  scale_x_continuous(expand = c(0,0), limits = c(0,2.5)) +
  scale_y_continuous(expand = expansion(mult = c(0,0)))

# multipion
events %>%
  filter(model == "1track") %>%
  ggplot(aes(ptmu, fill = Truth, color = Truth, weight = multipionBDTG*weight/0.1)) +
  stat_bin(colour = "black", binwidth = 0.1, origin = 0) +
  theme_bw() + ggtitle("multipion response weights, 1track") + ylab("events per GeV") +
  scale_x_continuous(expand = c(0,0), limits = c(0,2.5)) +
  scale_y_continuous(expand = expansion(mult = c(0, .1)))

events %>%
  filter(model == "1track") %>%
  ggplot(aes(ptmu, fill = Truth, color = Truth, weight = multipionBDTG*weight/0.1)) +
  stat_bin(colour = "black", binwidth = 0.1, origin = 0, position = "fill") +
  theme_bw() + ggtitle("multipion response weights") + ylab("event contributions") +
  scale_x_continuous(expand = c(0,0), limits = c(0,2.5)) +
  scale_y_continuous(expand = expansion(mult = c(0,0)))

# other
events %>%
  filter(model == "1track") %>%
  ggplot(aes(ptmu, fill = Truth, color = Truth, weight = otherBDTG*weight/0.1)) +
  stat_bin(colour = "black", binwidth = 0.1, origin = 0) +
  theme_bw() + ggtitle("other response weights, 1track") + ylab("events per GeV") +
  scale_x_continuous(expand = c(0,0), limits = c(0,2.5)) +
  scale_y_continuous(expand = expansion(mult = c(0, .1)))

events %>%
  filter(model == "1track") %>%
  ggplot(aes(ptmu, fill = Truth, color = Truth, weight = otherBDTG*weight/0.1)) +
  stat_bin(colour = "black", binwidth = 0.1, origin = 0, position = "fill") +
  theme_bw() + ggtitle("other response weights, 1track") + ylab("event contributions") +
  scale_x_continuous(expand = c(0,0), limits = c(0,2.5)) +
  scale_y_continuous(expand = expansion(mult = c(0,0)))
```

```{r, message = F, warning = F, echo = F, fig.height = 5, fig.width = 10}
events %>%
  ggplot(aes(ptmu, fill = Truth, color = Truth)) +
  stat_bin(colour = "black", binwidth = 0.1, origin = 0) +
  theme_bw() +
  scale_x_continuous(expand = c(0,0), limits = c(0,2.5)) +
  scale_y_continuous(expand = expansion(mult = c(0, .1)))

events %>%
  ggplot(aes(ptmu, fill = Truth, color = Truth)) +
  stat_bin(colour = "black", binwidth = 0.1, origin = 0) +
  theme_bw() +
  scale_x_continuous(expand = c(0,0), limits = c(0,2.5)) +
  scale_y_continuous(expand = expansion(mult = c(0, .1))) +
  facet_wrap(vars(Pred), ncol=2)

events %>%
  ggplot(aes(ptmu, fill = Truth, color = Truth)) +
  stat_bin(colour = "black", binwidth = 0.1, origin = 0) +
  theme_bw() +
  scale_x_continuous(expand = c(0,0), limits = c(0,2.5)) +
  scale_y_continuous(expand = expansion(mult = c(0, .1))) +
  facet_wrap(vars(Pred),scales="free_y", ncol=2)

events %>%
  ggplot(aes(ptmu, fill = Truth, color = Truth)) +
  stat_bin(colour = "black", binwidth = 0.1, position = "fill", origin = 0) +
  theme_bw() +
  scale_x_continuous(expand = c(0,0), limits = c(0,2.5)) +
  scale_y_continuous(expand = expansion(mult = c(0,0))) +
  facet_wrap(vars(Pred),scales="free_y", ncol=2)

events %>%
  filter(qelikeBDTG >= 0.35) %>%
  ggplot(aes(ptmu, fill = Truth, color = Truth)) +
  stat_bin(colour = "black", binwidth = 0.1, origin = 0) +
  theme_bw() + ggtitle("qelikeBDTG >= 0.35") +
  scale_x_continuous(expand = c(0,0), limits = c(0,2.5)) +
  scale_y_continuous(expand = expansion(mult = c(0,0))) +
  facet_wrap(vars(Pred),scales="free_y", ncol=2)

events %>%
  filter(qelikeBDTG >= 0.35) %>%
  ggplot(aes(ptmu, fill = Truth, color = Truth)) +
  stat_bin(colour = "black", binwidth = 0.1, position = "fill", origin = 0) +
  theme_bw() + ggtitle("qelikeBDTG >= 0.35") +
  scale_x_continuous(expand = c(0,0), limits = c(0,2.5)) +
  scale_y_continuous(expand = expansion(mult = c(0,0))) +
  facet_wrap(vars(Pred),scales="free_y", ncol=2)
```
```{r, message = F, warning = F, echo = F}
# multiplicity == 1
events %>%
  filter(Multiplicity == 1) %>%
  filter(Pred == "QELike") %>%
  ggplot(aes(ptmu, fill = Truth, color = Truth)) +
  stat_bin(colour = "black", binwidth = 0.1, origin = 0) +
  theme_bw() + ggtitle("qelikeBDTG is max, multiplicity = 1") +
  scale_x_continuous(expand = c(0,0), limits = c(0,2.5)) +
  scale_y_continuous(expand = expansion(mult = c(0,0.05)))

events %>%
  filter(Multiplicity == 1) %>%
  filter(qelikeBDTG >= 0.35) %>%
  ggplot(aes(ptmu, fill = Truth, color = Truth)) +
  stat_bin(colour = "black", binwidth = 0.1, origin = 0) +
  theme_bw() + ggtitle("qelikeBDTG >= 0.35, multiplicity = 1") +
  scale_x_continuous(expand = c(0,0), limits = c(0,2.5)) +
  scale_y_continuous(expand = expansion(mult = c(0,0.05)))

events %>%
  filter(Multiplicity == 1) %>%
  filter(Pred == "QELike") %>%
  ggplot(aes(ptmu, fill = Truth, color = Truth)) +
  stat_bin(colour = "black", position = "fill", binwidth = 0.1, origin = 0) +
  theme_bw() + ggtitle("qelikeBDTG is max, multiplicity = 1") +
  scale_x_continuous(expand = c(0,0), limits = c(0,2.5)) +
  scale_y_continuous(expand = expansion(mult = c(0,0.05)))

events %>%
  filter(Multiplicity == 1) %>%
  filter(qelikeBDTG >= 0.35) %>%
  ggplot(aes(ptmu, fill = Truth, color = Truth)) +
  stat_bin(colour = "black", position = "fill", binwidth = 0.1, origin = 0) +
  theme_bw() + ggtitle("qelikeBDTG >= 0.35, multiplicity = 1") +
  scale_x_continuous(expand = c(0,0), limits = c(0,2.5)) +
  scale_y_continuous(expand = expansion(mult = c(0,0.05)))

# multiplicity > 1
events %>%
  filter(Multiplicity > 1) %>%
  filter(Pred == "QELike") %>%
  ggplot(aes(ptmu, fill = Truth, color = Truth)) +
  stat_bin(colour = "black", binwidth = 0.1, origin = 0) +
  theme_bw() + ggtitle("qelikeBDTG is max, multiplicity > 1") +
  scale_x_continuous(expand = c(0,0), limits = c(0,2.5)) +
  scale_y_continuous(expand = expansion(mult = c(0,0.05)))

events %>%
  filter(Multiplicity > 1) %>%
  filter(qelikeBDTG >= 0.35) %>%
  ggplot(aes(ptmu, fill = Truth, color = Truth)) +
  stat_bin(colour = "black", binwidth = 0.1, origin = 0) +
  theme_bw() + ggtitle("qelikeBDTG >= 0.35, multiplicity > 1") +
  scale_x_continuous(expand = c(0,0), limits = c(0,2.5)) +
  scale_y_continuous(expand = expansion(mult = c(0,0.05)))

events %>%
  filter(Multiplicity > 1) %>%
  filter(Pred == "QELike") %>%
  ggplot(aes(ptmu, fill = Truth, color = Truth)) +
  stat_bin(colour = "black", position = "fill", binwidth = 0.1, origin = 0) +
  theme_bw() + ggtitle("qelikeBDTG is max, multiplicity > 1") +
  scale_x_continuous(expand = c(0,0), limits = c(0,2.5)) +
  scale_y_continuous(expand = expansion(mult = c(0,0.05)))

events %>%
  filter(Multiplicity > 1) %>%
  filter(qelikeBDTG >= 0.35) %>%
  ggplot(aes(ptmu, fill = Truth, color = Truth)) +
  stat_bin(colour = "black", position = "fill", binwidth = 0.1, origin = 0) +
  theme_bw() + ggtitle("qelikeBDTG >= 0.35, multiplicity > 1") +
  scale_x_continuous(expand = c(0,0), limits = c(0,2.5)) +
  scale_y_continuous(expand = expansion(mult = c(0,0.05)))

# multiplicity > 0
events %>%
  filter(Pred == "QELike") %>%
  ggplot(aes(qelikeBDTG, fill = Truth, color = Truth)) +
  stat_bin(colour = "black", binwidth = 0.05, origin = 0) +
  theme_bw() + ggtitle("qelikeBDTG is max") +
  scale_x_continuous(expand = c(0,0), limits = c(0,1)) +
  scale_y_continuous(expand = expansion(mult = c(0,0.05)))

events %>%
  filter(qelikeBDTG >= 0.35) %>%
  ggplot(aes(qelikeBDTG, fill = Truth, color = Truth)) +
  stat_bin(colour = "black", binwidth = 0.05, origin = 0) +
  theme_bw() + ggtitle("qelikeBDTG >= 0.35") +
  scale_x_continuous(expand = c(0,0), limits = c(0,1)) +
  scale_y_continuous(expand = expansion(mult = c(0,0.05)))
```
```{r, message = F, warning = F, echo = F}
events %>%
  filter(Multiplicity == 1) %>%
  ggplot(aes(qelikeBDTG,fill=Truth,color=Truth)) +
  stat_bin(colour = "black", binwidth = 0.05, origin = 0) +
  theme_bw() +
  ggtitle("qelikeBDTG, Multiplicity = 1") +
  scale_x_continuous(breaks = seq(0,1,0.1), expand = c(0,0), limits = c(-0.026,1.026)) +
  scale_y_continuous(expand = expansion(mult = c(0, .1)))

events %>%
  filter(Multiplicity > 1) %>%
  ggplot(aes(qelikeBDTG,fill=Truth,color=Truth)) +
  stat_bin(colour = "black", binwidth = 0.05, origin = 0) +
  theme_bw() +
  ggtitle("qelikeBDTG, Multiplicity > 1") +
  scale_x_continuous(breaks = seq(0,1,0.1), expand = c(0,0), limits = c(-0.026,1.026)) +
  scale_y_continuous(expand = expansion(mult = c(0, .1)))

events %>%
  filter(model == "1track") %>%
  ggplot(aes(qelikeBDTG,fill=Truth,color=Truth)) +
  stat_bin(colour = "black", binwidth = 0.05, origin = 0) +
  theme_bw() +
  ggtitle("qelikeBDTG, muon only") +
  scale_x_continuous(breaks = seq(0,1,0.1), expand = c(0,0), limits = c(-0.026,1.026)) +
  scale_y_continuous(expand = expansion(mult = c(0, .1)))

events %>%
  filter(model != "1track") %>%
  ggplot(aes(qelikeBDTG,fill=Truth,color=Truth)) +
  stat_bin(colour = "black", binwidth = 0.05, origin = 0) +
  theme_bw() +
  ggtitle("qelikeBDTG, muon + proton(s)") +
  scale_x_continuous(breaks = seq(0,1,0.1), expand = c(0,0), limits = c(-0.026,1.026)) +
  scale_y_continuous(expand = expansion(mult = c(0, .1)))

events %>%
  filter(qelikeBDTG > 0.3) %>%
  ggplot(aes(`1chargedpionBDTG`,fill=Truth,color=Truth)) +
  stat_bin(colour = "black", origin = 0) +
  theme_bw() +
  ggtitle("qelikeBDTG, muon + proton(s)") +
  scale_x_continuous(expand = c(0,0)) +
  scale_y_continuous(expand = expansion(mult = c(0,0.05)))
```

```{r, message = F, warning = F, echo = F, fig.height = 8, fig.width = 6}
events %>%
  filter(Multiplicity == 1) %>%
  ggplot(aes(qelikeBDTG,fill=Truth,color=Truth)) +
  stat_bin(colour = "black", binwidth = 0.05, origin = 0) +
  theme_bw() +
  ggtitle("qelikeBDTG, Multiplicity = 1") +
  scale_x_continuous(breaks = seq(0,1,0.1), expand = c(0,0), limits = c(-0.026,1.026)) +
  scale_y_continuous(expand = expansion(mult = c(0, .1))) +
  facet_wrap(vars(Truth),scales="free_y", ncol=1)

events %>%
  filter(Multiplicity > 1) %>%
  ggplot(aes(qelikeBDTG,fill=Truth,color=Truth)) +
  stat_bin(colour = "black", binwidth = 0.05, origin = 0) +
  theme_bw() +
  ggtitle("qelikeBDTG, Multiplicity > 1") +
  scale_x_continuous(breaks = seq(0,1,0.1), expand = c(0,0), limits = c(-0.026,1.026)) +
  scale_y_continuous(expand = expansion(mult = c(0, .1))) +
  facet_wrap(vars(Truth),scales="free_y", ncol=1)

events %>%
  filter(model == "1track") %>%
  ggplot(aes(qelikeBDTG,fill=Truth,color=Truth)) +
  stat_bin(colour = "black", binwidth = 0.05, origin = 0) +
  theme_bw() +
  ggtitle("qelikeBDTG, muon only") +
  scale_x_continuous(breaks = seq(0,1,0.1), expand = c(0,0), limits = c(-0.026,1.026)) +
  scale_y_continuous(expand = expansion(mult = c(0, .1))) +
  facet_wrap(vars(Truth),scales="free_y", ncol=1)

events %>%
  filter(model != "1track") %>%
  ggplot(aes(qelikeBDTG,fill=Truth,color=Truth)) +
  stat_bin(colour = "black", binwidth = 0.05, origin = 0) +
  theme_bw() +
  ggtitle("qelikeBDTG, muon + proton(s)") +
  scale_x_continuous(breaks = seq(0,1,0.1), expand = c(0,0), limits = c(-0.026,1.026)) +
  scale_y_continuous(expand = expansion(mult = c(0, .1))) +
  facet_wrap(vars(Truth),scales="free_y", ncol=1)


```


```{r, message = F, warning = F, echo = F}
events %>%
  ggplot(aes(qelikeBDTG,fill=Truth,color=Truth)) +
  stat_bin(colour = "black", binwidth = 0.05, origin = 0) +
  theme_bw() +
  ggtitle("qelikeBDTG") +
  scale_x_continuous(breaks = seq(0,1,0.1), expand = c(0,0), limits = c(-0.026,1.026)) +
  scale_y_continuous(expand = expansion(mult = c(0, .1))) +
  facet_wrap(vars(model),scales="free_y", ncol=1)

events %>%
  ggplot(aes(`1chargedpionBDTG`,fill=Truth,color=Truth)) +
  stat_bin(colour = "black", binwidth = 0.05, origin = 0) +
  theme_bw() +
  ggtitle("1chargedpionBDTG") +
  scale_x_continuous(breaks = seq(0,1,0.1), expand = c(0,0), limits = c(-0.025,1.025)) +
  scale_y_continuous(expand = expansion(mult = c(0, .1))) +
  facet_wrap(vars(model),scales="free_y", ncol=1)

events %>%
  ggplot(aes(`1neutralpionBDTG`,fill=Truth,color=Truth)) +
  stat_bin(colour = "black", binwidth = 0.05, origin = 0) +
  theme_bw() +
  ggtitle("1neutralpionBDTG") +
  scale_x_continuous(breaks = seq(0,1,0.1), expand = c(0,0), limits = c(-0.025,1.025)) +
  scale_y_continuous(expand = expansion(mult = c(0, .1))) +
  facet_wrap(vars(model),scales="free_y", ncol=1)

events %>%
  ggplot(aes(multipionBDTG,fill=Truth,color=Truth)) +
  stat_bin(colour = "black", binwidth = 0.05, origin = 0) +
  theme_bw() +
  ggtitle("multipionBDTG") +
  scale_x_continuous(breaks = seq(0,1,0.1), expand = c(0,0), limits = c(-0.025,1.025)) +
  scale_y_continuous(expand = expansion(mult = c(0, .1))) +
  facet_wrap(vars(model),scales="free_y", ncol=1)

events %>%
  ggplot(aes(otherBDTG,fill=Truth,color=Truth)) +
  stat_bin(colour = "black", binwidth = 0.05, origin = 0) +
  theme_bw() +
  ggtitle("otherBDTG") +
  scale_x_continuous(breaks = seq(0,1,0.1), expand = c(0,0), limits = c(-0.025,1.025)) +
  scale_y_continuous(expand = expansion(mult = c(0, .1))) +
  facet_wrap(vars(model),scales="free_y", ncol=1)
```
```{r, message = F, warning = F, echo = F}
events %>%
  ggplot(aes(qelikeBDTG,fill=Truth,color=Truth)) +
  stat_bin(colour = "black",  position = 'fill', binwidth = 0.05, origin = 0) +
  theme_bw() +
  ggtitle("qelikeBDTG") +
  scale_x_continuous(breaks = seq(0,1,0.1), expand = c(0,0), limits = c(0,1)) +
  scale_y_continuous(expand = expansion(mult = c(0,0))) +
  facet_wrap(vars(model),scales="free_y", ncol=1)

events %>%
  ggplot(aes(`1chargedpionBDTG`,fill=Truth,color=Truth)) +
  stat_bin(colour = "black", position = 'fill', binwidth = 0.05, origin = 0) +
  theme_bw() +
  ggtitle("1chargedpionBDTG") +
  scale_x_continuous(breaks = seq(0,1,0.1), expand = c(0,0), limits = c(0,1)) +
  scale_y_continuous(expand = expansion(mult = c(0,0))) +
  facet_wrap(vars(model),scales="free_y", ncol=1)

events %>%
  ggplot(aes(`1neutralpionBDTG`,fill=Truth,color=Truth)) +
  stat_bin(colour = "black", position = 'fill', binwidth = 0.05, origin = 0) +
  theme_bw() +
  ggtitle("1neutralpionBDTG") +
  scale_x_continuous(breaks = seq(0,1,0.1), expand = c(0,0), limits = c(0,1)) +
  scale_y_continuous(expand = expansion(mult = c(0, .1))) +
  facet_wrap(vars(model),scales="free_y", ncol=1)

events %>%
  ggplot(aes(multipionBDTG,fill=Truth,color=Truth)) +
  stat_bin(colour = "black", position = 'fill', binwidth = 0.05, origin = 0) +
  theme_bw() +
  ggtitle("multipionBDTG") +
  scale_x_continuous(breaks = seq(0,1,0.1), expand = c(0,0), limits = c(0,1)) +
  scale_y_continuous(expand = expansion(mult = c(0, .1))) +
  facet_wrap(vars(model),scales="free_y", ncol=1)
```
```{r, message = F, warning = F, echo = F}
cbind(
  events %>%
    count(Truth) %>%
    mutate(N = n) %>%
    dplyr::select(Truth,N),
  events %>%
    filter(multipionBDTG >= 0.4) %>%
    count(Truth) %>%
    dplyr::select(n)
) %>%
  mutate(`n/N %` = signif(100*n/N,4)) %>%
  mutate(`n/Sum n %` = signif(100*n/sum(n),4))

cbind(
  events %>%
    filter(Multiplicity == 1) %>%
    count(Truth) %>%
    mutate(N = n) %>%
    dplyr::select(Truth,N),
  events %>%
    filter(Multiplicity == 1) %>%
    filter(qelikeBDTG >= 0.35) %>%
    count(Truth) %>%
    dplyr::select(n)
) %>%
  mutate(`n/N %` = signif(100*n/N,4)) %>%
  mutate(`n/Sum n %` = signif(100*n/sum(n),4))

cbind(
  events %>%
    count(Truth) %>%
    mutate(N = n) %>%
    dplyr::select(Truth,N),
  events %>%
    filter(qelikeBDTG >= 0.35) %>%
    count(Truth) %>%
    dplyr::select(n)
) %>%
  mutate(`n/N %` = signif(100*n/N,4)) %>%
  mutate(`n/Sum n %` = signif(100*n/sum(n),4))

cbind(
  events %>%
    count(Truth) %>%
    mutate(N = n) %>%
    dplyr::select(Truth,N),
  events %>%
    filter(Pred == "QELike") %>% 
    count(Truth) %>%
    dplyr::select(n)
) %>%
  mutate(`n/N %` = signif(100*n/N,4)) %>%
  mutate(`n/Sum n %` = signif(100*n/sum(n),4))

```
```{r, message = F, warning = F, echo = F}
events %>% group_by(Truth) %>% count()
x = seq(0,1,0.01)
y1 = c()
for(i in x){
  n1 <- nrow(events %>% filter(Multiplicity == 1 & Truth == "qelike" & qelikeBDTG >= i))
  n2 <- nrow(events %>% filter(Multiplicity == 1 & Truth == "qelike"))
  y1 <- c(y1,n1/n2)
}
y2 = c()
for(i in x){
  n1 <- nrow(events %>% filter(Multiplicity == 1 & Truth == "qelike" & qelikeBDTG >= i))
  n2 <- nrow(events %>% filter(Multiplicity == 1 & qelikeBDTG >= i))
  y2 <- c(y2,n1/n2)
}
y3 = c()
for(i in x){
  n1 <- nrow(events %>% filter(Multiplicity == 2 & Truth == "qelike" & qelikeBDTG >= i))
  n2 <- nrow(events %>% filter(Multiplicity == 2 & Truth == "qelike"))
  y3 <- c(y3,n1/n2)
}
y4 = c()
for(i in x){
  n1 <- nrow(events %>% filter(Multiplicity == 2 & Truth == "qelike" & qelikeBDTG >= i))
  n2 <- nrow(events %>% filter(Multiplicity == 2 & qelikeBDTG >= i))
  y4 <- c(y4,n1/n2)
}

plot(x,y1,col=2)
points(x,y2,col=4)
points(x,y1*y2,col=3)

plot(x,y3,col=2)
points(x,y4,col=4)
points(x,y3*y4,col=3)

m1 <- which.max(y1*y2)
m2 <- which.max(y3*y4)
x[m1]
x[m2]

plot(x[(m1-5):(m1+5)],y1[(m1-5):(m1+5)],col=2, ylim = c(0.6,0.9))
points(x[(m1-5):(m1+5)],y2[(m1-5):(m1+5)],col=4)
points(x[(m1-5):(m1+5)],(y1*y2)[(m1-5):(m1+5)],col=3)

plot(x[(m2-5):(m2+5)],y3[(m2-5):(m2+5)],col=2, ylim = c(0.4,0.8))
points(x[(m2-5):(m2+5)],y4[(m2-5):(m2+5)],col=4)
points(x[(m2-5):(m2+5)],(y3*y4)[(m2-5):(m2+5)],col=3)



cbind(x,(y1*y2))
cbind(x,(y3*y4))
```
```{r, message = F, warning = F, echo = F}

x = seq(0,1,0.01)
y1 = c()
for(i in x){
  n1 <- nrow(events %>% filter(PrimaryProtonScore1 < 0 & Truth == "qelike" & qelikeBDTG >= i))
  n2 <- nrow(events %>% filter(PrimaryProtonScore1 < 0 & Truth == "qelike"))
  y1 <- c(y1,n1/n2)
}
y2 = c()
for(i in x){
  n1 <- nrow(events %>% filter(PrimaryProtonScore1 < 0 & Truth == "qelike" & qelikeBDTG >= i))
  n2 <- nrow(events %>% filter(PrimaryProtonScore1 < 0 & qelikeBDTG >= i))
  y2 <- c(y2,n1/n2)
}
y3 = c()
for(i in x){
  n1 <- nrow(events %>% filter(PrimaryProtonScore1 >= 0 & Truth == "qelike" & qelikeBDTG >= i))
  n2 <- nrow(events %>% filter(PrimaryProtonScore1 >= 0 & Truth == "qelike"))
  y3 <- c(y3,n1/n2)
}
y4 = c()
for(i in x){
  n1 <- nrow(events %>% filter(PrimaryProtonScore1 >= 0 & Truth == "qelike" & qelikeBDTG >= i))
  n2 <- nrow(events %>% filter(PrimaryProtonScore1 >= 0 & qelikeBDTG >= i))
  y4 <- c(y4,n1/n2)
}

plot(x,y1,col=2)
points(x,y2,col=4)
points(x,y1*y2,col=3)

plot(x,y3,col=2)
points(x,y4,col=4)
points(x,y3*y4,col=3)

m1 <- which.max(y1*y2)
m2 <- which.max(y3*y4)
x[m1]
x[m2]

```

```{r, message = F, warning = F, echo = F}
events %>%
  filter(multipionBDTG < 0.4) %>%
  ggplot(aes(qelikeBDTG,fill=Truth,color=Truth)) +
  stat_bin(colour = "black", binwidth = 0.05, origin = 0) +
  theme_bw() +
  ggtitle("qelikeBDTG") +
  scale_x_continuous(breaks = seq(0,1,0.1), expand = c(0,0), limits = c(-0.026,1.026)) +
  scale_y_continuous(expand = expansion(mult = c(0, .1))) +
  facet_wrap(vars(model),scales="free_y", ncol=1)

events %>%
  filter(multipionBDTG < 0.4) %>%
  ggplot(aes(`1chargedpionBDTG`,fill=Truth,color=Truth)) +
  stat_bin(colour = "black", binwidth = 0.05, origin = 0) +
  theme_bw() +
  ggtitle("1chargedpionBDTG") +
  scale_x_continuous(breaks = seq(0,1,0.1), expand = c(0,0), limits = c(-0.025,1.025)) +
  scale_y_continuous(expand = expansion(mult = c(0, .1))) +
  facet_wrap(vars(model),scales="free_y", ncol=1)

events %>%
  filter(multipionBDTG < 0.4) %>%
  ggplot(aes(`1neutralpionBDTG`,fill=Truth,color=Truth)) +
  stat_bin(colour = "black", binwidth = 0.05, origin = 0) +
  theme_bw() +
  ggtitle("1neutralpionBDTG") +
  scale_x_continuous(breaks = seq(0,1,0.1), expand = c(0,0), limits = c(-0.025,1.025)) +
  scale_y_continuous(expand = expansion(mult = c(0, .1))) +
  facet_wrap(vars(model),scales="free_y", ncol=1)
```

```{r, message = F, warning = F, echo = F}
events %>%
  filter(multipionBDTG < 0.4) %>%
  ggplot(aes(qelikeBDTG,fill=Truth,color=Truth)) +
  stat_bin(colour = "black",  position = 'fill', binwidth = 0.05, origin = 0) +
  theme_bw() +
  ggtitle("qelikeBDTG") +
  scale_x_continuous(breaks = seq(0,1,0.1), expand = c(0,0), limits = c(0,1)) +
  scale_y_continuous(expand = expansion(mult = c(0,0))) +
  facet_wrap(vars(model),scales="free_y", ncol=1)

events %>%
  filter(multipionBDTG < 0.4) %>%
  ggplot(aes(`1chargedpionBDTG`,fill=Truth,color=Truth)) +
  stat_bin(colour = "black", position = 'fill', binwidth = 0.05, origin = 0) +
  theme_bw() +
  ggtitle("1chargedpionBDTG") +
  scale_x_continuous(breaks = seq(0,1,0.1), expand = c(0,0), limits = c(0,1)) +
  scale_y_continuous(expand = expansion(mult = c(0,0))) +
  facet_wrap(vars(model),scales="free_y", ncol=1)

events %>%
  filter(multipionBDTG < 0.4) %>%
  ggplot(aes(`1neutralpionBDTG`,fill=Truth,color=Truth)) +
  stat_bin(colour = "black", position = 'fill', binwidth = 0.05, origin = 0) +
  theme_bw() +
  ggtitle("1neutralpionBDTG") +
  scale_x_continuous(breaks = seq(0,1,0.1), expand = c(0,0), limits = c(0,1)) +
  scale_y_continuous(expand = expansion(mult = c(0, .1))) +
  facet_wrap(vars(model),scales="free_y", ncol=1)
```
```{r, message = F, warning = F, echo = F}
cbind(
  events %>%
    count(Truth) %>%
    mutate(N = n) %>%
    dplyr::select(Truth,N),
  events %>%
    filter(multipionBDTG < 0.4) %>%
    filter(qelikeBDTG >= 0.4) %>%
    count(Truth) %>%
    dplyr::select(n)
) %>%
  mutate(`n/N %` = signif(100*n/N,4)) %>%
  mutate(`n/Sum n %` = signif(100*n/sum(n),4))
```
```{r, message = F, warning = F, echo = F}
events %>%
  filter(multipionBDTG < 0.4) %>%
  filter(qelikeBDTG < 0.4) %>%
  ggplot(aes(`1chargedpionBDTG`,fill=Truth,color=Truth)) +
  stat_bin(colour = "black", binwidth = 0.05, origin = 0) +
  theme_bw() +
  ggtitle("1chargedpionBDTG") +
  scale_x_continuous(breaks = seq(0,1,0.1), expand = c(0,0), limits = c(-0.025,1.025)) +
  scale_y_continuous(expand = expansion(mult = c(0, .1))) +
  facet_wrap(vars(model),scales="free_y", ncol=1)

events %>%
  filter(multipionBDTG < 0.4) %>%
  filter(qelikeBDTG < 0.4) %>%
  ggplot(aes(`1neutralpionBDTG`,fill=Truth,color=Truth)) +
  stat_bin(colour = "black", binwidth = 0.05, origin = 0) +
  theme_bw() +
  ggtitle("1neutralpionBDTG") +
  scale_x_continuous(breaks = seq(0,1,0.1), expand = c(0,0), limits = c(-0.025,1.025)) +
  scale_y_continuous(expand = expansion(mult = c(0, .1))) +
  facet_wrap(vars(model),scales="free_y", ncol=1)
```

```{r, message = F, warning = F, echo = F}
events %>%
  filter(multipionBDTG < 0.4) %>%
  filter(qelikeBDTG < 0.4) %>%
  ggplot(aes(`1chargedpionBDTG`,fill=Truth,color=Truth)) +
  stat_bin(colour = "black", position = 'fill', binwidth = 0.05, origin = 0) +
  theme_bw() +
  ggtitle("1chargedpionBDTG") +
  scale_x_continuous(breaks = seq(0,1,0.1), expand = c(0,0), limits = c(0,1)) +
  scale_y_continuous(expand = expansion(mult = c(0,0))) +
  facet_wrap(vars(model),scales="free_y", ncol=1)

events %>%
  filter(multipionBDTG < 0.4) %>%
  filter(qelikeBDTG < 0.4) %>%
  ggplot(aes(`1neutralpionBDTG`,fill=Truth,color=Truth)) +
  stat_bin(colour = "black", position = 'fill', binwidth = 0.05, origin = 0) +
  theme_bw() +
  ggtitle("1neutralpionBDTG") +
  scale_x_continuous(breaks = seq(0,1,0.1), expand = c(0,0), limits = c(0,1)) +
  scale_y_continuous(expand = expansion(mult = c(0, .1))) +
  facet_wrap(vars(model),scales="free_y", ncol=1)
```
```{r, message = F, warning = F, echo = F}
cbind(
  events %>%
    count(Truth) %>%
    mutate(N = n) %>%
    dplyr::select(Truth,N),
  events %>%
    filter(multipionBDTG < 0.4) %>%
    filter(qelikeBDTG < 0.4) %>%
    filter(`1chargedpionBDTG` >= 0.4) %>%
    count(Truth) %>%
    dplyr::select(n)
) %>%
  mutate(`n/N %` = signif(100*n/N,4)) %>%
  mutate(`n/Sum n %` = signif(100*n/sum(n),4))
```
```{r, message = F, warning = F, echo = F}
events %>%
  filter(multipionBDTG < 0.4) %>%
  filter(qelikeBDTG < 0.4) %>%
  filter(`1chargedpionBDTG` < 0.4) %>%
  ggplot(aes(`1neutralpionBDTG`,fill=Truth,color=Truth)) +
  stat_bin(colour = "black", binwidth = 0.05, origin = 0) +
  theme_bw() +
  ggtitle("1neutralpionBDTG") +
  scale_x_continuous(breaks = seq(0,1,0.1), expand = c(0,0), limits = c(-0.025,1.025)) +
  scale_y_continuous(expand = expansion(mult = c(0, .1))) +
  facet_wrap(vars(model),scales="free_y", ncol=1)
```

```{r, message = F, warning = F, echo = F}
events %>%
  filter(multipionBDTG < 0.4) %>%
  filter(qelikeBDTG < 0.4) %>%
  filter(`1chargedpionBDTG` < 0.4) %>%
  ggplot(aes(`1neutralpionBDTG`,fill=Truth,color=Truth)) +
  stat_bin(colour = "black", position = 'fill', binwidth = 0.05, origin = 0) +
  theme_bw() +
  ggtitle("1neutralpionBDTG") +
  scale_x_continuous(breaks = seq(0,1,0.1), expand = c(0,0), limits = c(0,1)) +
  scale_y_continuous(expand = expansion(mult = c(0, .1))) +
  facet_wrap(vars(model),scales="free_y", ncol=1)

events %>%
  filter(multipionBDTG < 0.4) %>%
  filter(qelikeBDTG < 0.4) %>%
  filter(`1chargedpionBDTG` < 0.4) %>%
  ggplot(aes(`otherBDTG`,fill=Truth,color=Truth)) +
  stat_bin(colour = "black", position = 'fill', binwidth = 0.05, origin = 0) +
  theme_bw() +
  ggtitle("1neutralpionBDTG") +
  scale_x_continuous(breaks = seq(0,1,0.1), expand = c(0,0), limits = c(0,1)) +
  scale_y_continuous(expand = expansion(mult = c(0, .1))) +
  facet_wrap(vars(model),scales="free_y", ncol=1)
```
```{r, message = F, warning = F, echo = F, eval = F}
events = events %>%
  mutate(isMultipion = case_when(Truth == "multipion" ~ 1, .default = 0)) %>%
  mutate(isQELike = case_when(Truth == "qelike" ~ 1, .default = 0)) %>%
  mutate(is1ChargedPion = case_when(Truth == "1chargedpion" ~ 1, .default = 0))

events[,c("isMultipion","qelikeBDTG","1chargedpionBDTG","1neutralpionBDTG","multipionBDTG","otherBDTG")]

logit_qelike_1 <- glm(isQELike~., family = binomial,
                         data = events[,c("isQELike","qelikeBDTG","1chargedpionBDTG","1neutralpionBDTG","multipionBDTG","otherBDTG")])
summary(logit_qelike_1)

logit_multipion_2 <- stepAIC(logit_multipion_1)
summary(logit_multipion_2)

logit_multipion_2$fitted.values

events %>%
  mutate(logit_qelike = logit_qelike_1$fitted.values) %>%
  ggplot(aes(`logit_qelike`,fill=Truth,color=Truth)) +
  stat_bin(colour = "black", binwidth = 0.05, origin = 0) +
  theme_bw() +
  ggtitle("logit_qelike") +
  scale_x_continuous(breaks = seq(0,1,0.1), expand = c(0,0), limits = c(-0.025,1.025)) +
  scale_y_continuous(expand = expansion(mult = c(0, .1))) +
  facet_wrap(vars(model),scales="free_y", ncol=1)

events %>%
  ggplot(aes(`qelikeBDTG`,fill=Truth,color=Truth)) +
  stat_bin(colour = "black", binwidth = 0.05, origin = 0) +
  theme_bw() +
  ggtitle("qelikeBDTG") +
  scale_x_continuous(breaks = seq(0,1,0.1), expand = c(0,0), limits = c(-0.025,1.025)) +
  scale_y_continuous(expand = expansion(mult = c(0, .1))) +
  facet_wrap(vars(model),scales="free_y", ncol=1)

events %>%
  mutate(logit_qelike = logit_qelike_1$fitted.values) %>%
  ggplot(aes(`logit_qelike`,fill=Truth,color=Truth)) +
  stat_bin(colour = "black", position = 'fill', binwidth = 0.05, origin = 0) +
  theme_bw() +
  ggtitle("logit_qelike") +
  scale_x_continuous(breaks = seq(0,1,0.1), expand = c(0,0), limits = c(0,1)) +
  scale_y_continuous(expand = expansion(mult = c(0, .1))) +
  facet_wrap(vars(model),scales="free_y", ncol=1)

events %>%
  ggplot(aes(`qelikeBDTG`,fill=Truth,color=Truth)) +
  stat_bin(colour = "black", position = 'fill', binwidth = 0.05, origin = 0) +
  theme_bw() +
  ggtitle("qelikeBDTG") +
  scale_x_continuous(breaks = seq(0,1,0.1), expand = c(0,0), limits = c(0,1)) +
  scale_y_continuous(expand = expansion(mult = c(0, .1))) +
  facet_wrap(vars(model),scales="free_y", ncol=1)
```

```{r, message = F, warning = F, echo = F, eval = F}
cbind(
  events %>%
    count(Truth) %>%
    mutate(N = n) %>%
    dplyr::select(Truth,N),
  events %>%
    filter(qelikeBDTG >= 0.4) %>%
    count(Truth) %>%
    dplyr::select(n)
) %>%
  mutate(`n/N %` = signif(100*n/N,4)) %>%
  mutate(`n/Sum n %` = signif(100*n/sum(n),4))

cbind(
  events %>%
    count(Truth) %>%
    mutate(N = n) %>%
    dplyr::select(Truth,N),
  events %>%
    mutate(logit_qelike = logit_qelike_1$fitted.values) %>%
    filter(logit_qelike >= 0.4) %>%
    count(Truth) %>%
    dplyr::select(n)
) %>%
  mutate(`n/N %` = signif(100*n/N,4)) %>%
  mutate(`n/Sum n %` = signif(100*n/sum(n),4))
```

```{r, message = F, warning = F, echo = F}
library(scico)

my_fn <- function(data, mapping, ...){
  # Using default ggplot density function
  p <- ggplot(data = data, mapping = mapping) + 
    stat_density2d(aes(fill=..density..), geom="tile", n=20, contour = FALSE) +
    scale_fill_stepsn(n.breaks = 13, colours = c("#FFFFFFFF",viridis::viridis(12)))
  p
}

ggpairs(events %>%
    dplyr::select(qelikeBDTG,`1chargedpionBDTG`,`1neutralpionBDTG`,
                  multipionBDTG,otherBDTG,Truth) %>%
    filter(Truth == "qelike"), columns = 1:5, lower=list(continuous=my_fn)) +
  theme_bw() + ggtitle("qelike") +
  scale_x_continuous(expand = c(0,0)) +
  scale_y_continuous(expand = c(0,0))
ggpairs(events %>%
    dplyr::select(qelikeBDTG,`1chargedpionBDTG`,`1neutralpionBDTG`,
                  multipionBDTG,otherBDTG,Truth) %>%
    filter(Truth == "1chargedpion"), columns = 1:5, lower=list(continuous=my_fn)) +
  theme_bw() + ggtitle("1chargedpion") +
  theme(legend.position = "right") +
  scale_x_continuous(expand = c(0,0)) +
  scale_y_continuous(expand = c(0,0))
ggpairs(events %>%
    dplyr::select(qelikeBDTG,`1chargedpionBDTG`,`1neutralpionBDTG`,
                  multipionBDTG,otherBDTG,Truth) %>%
    filter(Truth == "1neutralpion"), columns = 1:5, lower=list(continuous=my_fn)) +
  theme_bw() + ggtitle("1neturalpion") +
  scale_x_continuous(expand = c(0,0)) +
  scale_y_continuous(expand = c(0,0))
ggpairs(events %>%
    dplyr::select(qelikeBDTG,`1chargedpionBDTG`,`1neutralpionBDTG`,
                  multipionBDTG,otherBDTG,Truth) %>%
    filter(Truth == "multipion"), columns = 1:5, lower=list(continuous=my_fn)) +
  theme_bw() + ggtitle("multipion") +
  scale_x_continuous(expand = c(0,0)) +
  scale_y_continuous(expand = c(0,0))
ggpairs(events %>%
    dplyr::select(qelikeBDTG,`1chargedpionBDTG`,`1neutralpionBDTG`,
                  multipionBDTG,otherBDTG,Truth) %>%
    filter(Truth == "other"), columns = 1:5, lower=list(continuous=my_fn)) +
  theme_bw() + ggtitle("other") +
  scale_x_continuous(expand = c(0,0)) +
  scale_y_continuous(expand = c(0,0))
ggpairs(events %>%
    dplyr::select(qelikeBDTG,`1chargedpionBDTG`,`1neutralpionBDTG`,
                  multipionBDTG,otherBDTG,Truth), columns = 1:5, lower=list(continuous=my_fn)) +
  theme_bw() + ggtitle("All") +
  scale_x_continuous(expand = c(0,0)) +
  scale_y_continuous(expand = c(0,0))
  
```

```{r, message = F, warning = F, echo = F}
events2 = (events %>% filter(Truth != "other"))
events2$Truth = factor(events2$Truth)
events2$target = as.numeric(events2$Truth)
events2$target = events2$target-1

evts_1track <- events2 %>% filter(tracks == "1track")
evts_2track <- events2 %>% filter(tracks == "2track")
evts_3ptrack <- events2 %>% filter(tracks == "3ptrack")

evts_1track <- evts_1track[,c("Truth","Q2QE","qelikeBDTG","1chargedpionBDTG","1neutralpionBDTG","multipionBDTG")]
evts_2track <- evts_2track[,c("Truth","Q2QE","qelikeBDTG","1chargedpionBDTG","1neutralpionBDTG","multipionBDTG")]
evts_3ptrack <- evts_3ptrack[,c("Truth","Q2QE","qelikeBDTG","1chargedpionBDTG","1neutralpionBDTG","multipionBDTG")]

data_split_1track <- initial_split(evts_1track, prop = 0.75)
data_split_2track <- initial_split(evts_2track, prop = 0.75)
data_split_3ptrack <- initial_split(evts_3ptrack, prop = 0.75)

train_data_1track <- training(data_split_1track)
train_data_2track <- training(data_split_2track)
train_data_3ptrack <- training(data_split_3ptrack)

test_data_1track <- testing(data_split_1track)
test_data_2track <- testing(data_split_2track)
test_data_3ptrack <- testing(data_split_3ptrack)

evts_3ptrack %>% group_by(Truth) %>% count()
```

```{r, message = F, warning = F, echo = F}
tree_spec <- decision_tree(tree_depth = 20) %>%
 set_engine("rpart") %>%
 set_mode("classification")

tree_fit_1track <- tree_spec %>%
 fit(Truth ~ ., data = train_data_1track)
tree_fit_2track <- tree_spec %>%
 fit(Truth ~ ., data = train_data_2track)
tree_fit_3ptrack <- tree_spec %>%
 fit(Truth ~ ., data = train_data_3ptrack)

# Make predictions on the testing data
predictions_1track <- tree_fit_1track %>%
 predict(test_data_1track) %>%
 pull(.pred_class)
predictions_2track <- tree_fit_2track %>%
 predict(test_data_2track) %>%
 pull(.pred_class)
predictions_3ptrack <- tree_fit_3ptrack %>%
 predict(test_data_3ptrack) %>%
 pull(.pred_class)

# Confusion Matrices
confusionMatrix(predictions_1track, test_data_1track$Truth)
confusionMatrix(predictions_2track, test_data_2track$Truth)
confusionMatrix(predictions_3ptrack, test_data_3ptrack$Truth)

```

```{r, message = F, warning = F, echo = F}
evts_1track <- evts_1track %>%
  mutate(`qelikeBDTG`= `qelikeBDTG`/max(evts_1track$`qelikeBDTG`)) %>%
  mutate(`1chargedpionBDTG`= `1chargedpionBDTG`/max(evts_1track$`1chargedpionBDTG`)) %>%
  mutate(`1neutralpionBDTG`= `1neutralpionBDTG`/max(evts_1track$`1neutralpionBDTG`)) %>%
  mutate(`multipionBDTG`= `multipionBDTG`/max(evts_1track$`multipionBDTG`))
evts_2track <- evts_2track %>%
  mutate(`qelikeBDTG`= `qelikeBDTG`/max(evts_2track$`qelikeBDTG`)) %>%
  mutate(`1chargedpionBDTG`= `1chargedpionBDTG`/max(evts_2track$`1chargedpionBDTG`)) %>%
  mutate(`1neutralpionBDTG`= `1neutralpionBDTG`/max(evts_2track$`1neutralpionBDTG`)) %>%
  mutate(`multipionBDTG`= `multipionBDTG`/max(evts_2track$`multipionBDTG`))
evts_3ptrack <- evts_3ptrack %>%
  mutate(`qelikeBDTG`= `qelikeBDTG`/max(evts_3ptrack$`qelikeBDTG`)) %>%
  mutate(`1chargedpionBDTG`= `1chargedpionBDTG`/max(evts_3ptrack$`1chargedpionBDTG`)) %>%
  mutate(`1neutralpionBDTG`= `1neutralpionBDTG`/max(evts_3ptrack$`1neutralpionBDTG`)) %>%
  mutate(`multipionBDTG`= `multipionBDTG`/max(evts_3ptrack$`multipionBDTG`))

cats <- c("qelike","1chargedpion","1neutralpion","multipion")
evts_1track$prediction <- map_chr(1:nrow(evts_1track),~cats[which.max(evts_1track[.,c("qelikeBDTG","1chargedpionBDTG","1neutralpionBDTG","multipionBDTG")])])
evts_2track$prediction <- map_chr(1:nrow(evts_2track),~cats[which.max(evts_2track[.,c("qelikeBDTG","1chargedpionBDTG","1neutralpionBDTG","multipionBDTG")])])
evts_3ptrack$prediction <- map_chr(1:nrow(evts_3ptrack),~cats[which.max(evts_3ptrack[.,c("qelikeBDTG","1chargedpionBDTG","1neutralpionBDTG","multipionBDTG")])])

evts_1track$prediction <- factor(evts_1track$prediction)
evts_2track$prediction <- factor(evts_2track$prediction)
evts_3ptrack$prediction <- factor(evts_3ptrack$prediction)

confusionMatrix(evts_1track$prediction, evts_1track$Truth)
confusionMatrix(evts_2track$prediction, evts_2track$Truth)
confusionMatrix(evts_3ptrack$prediction, evts_3ptrack$Truth)

evts_1track %>% 
  ggplot(aes(Q2QE, fill = Truth, color = Truth)) +
  stat_bin(colour = "black", binwidth = 0.1, origin = 0) +
  theme_bw() + ggtitle("1track") +
  scale_x_continuous(expand = c(0,0), limits = c(0,3)) +
  scale_y_continuous(expand = expansion(mult = c(0,0.05))) +
  facet_wrap(vars(prediction), scales = "free_y")
evts_1track %>% 
  ggplot(aes(Q2QE, fill = Truth, color = Truth)) +
  stat_bin(colour = "black", position = "fill", binwidth = 0.1, origin = 0) +
  theme_bw() + ggtitle("1track") +
  scale_x_continuous(expand = c(0,0), limits = c(0,3)) +
  scale_y_continuous(expand = expansion(mult = c(0,0))) +
  facet_wrap(vars(prediction), scales = "free_y")

evts_2track %>% 
  ggplot(aes(Q2QE, fill = Truth, color = Truth)) +
  stat_bin(colour = "black", binwidth = 0.1, origin = 0) +
  theme_bw() + ggtitle("2track") +
  scale_x_continuous(expand = c(0,0), limits = c(0,3)) +
  scale_y_continuous(expand = expansion(mult = c(0,0.05))) +
  facet_wrap(vars(prediction), scales = "free_y")
evts_2track %>% 
  ggplot(aes(Q2QE, fill = Truth, color = Truth)) +
  stat_bin(colour = "black", position = "fill", binwidth = 0.1, origin = 0) +
  theme_bw() + ggtitle("2track") +
  scale_x_continuous(expand = c(0,0), limits = c(0,3)) +
  scale_y_continuous(expand = expansion(mult = c(0,0))) +
  facet_wrap(vars(prediction), scales = "free_y")

evts_3ptrack %>% 
  ggplot(aes(Q2QE, fill = Truth, color = Truth)) +
  stat_bin(colour = "black", binwidth = 0.1, origin = 0) +
  theme_bw() + ggtitle("3ptrack") +
  scale_x_continuous(expand = c(0,0), limits = c(0,3)) +
  scale_y_continuous(expand = expansion(mult = c(0,0.05))) +
  facet_wrap(vars(prediction), scales = "free_y")
evts_3ptrack %>% 
  ggplot(aes(Q2QE, fill = Truth, color = Truth)) +
  stat_bin(colour = "black", position = "fill", binwidth = 0.1, origin = 0) +
  theme_bw() + ggtitle("3ptrack") +
  scale_x_continuous(expand = c(0,0), limits = c(0,3)) +
  scale_y_continuous(expand = expansion(mult = c(0,0))) +
  facet_wrap(vars(prediction), scales = "free_y")
```

```{r, message = F, warning = F, echo = F}
# Make split index
train_index_1track <- sample(1:nrow(evts_1track), nrow(evts_1track)*0.75)
train_index_2track <- sample(1:nrow(evts_2track), nrow(evts_2track)*0.75)
train_index_3ptrack <- sample(1:nrow(evts_3ptrack), nrow(evts_3ptrack)*0.75)
# Full data set
data_variables_1track <- as.matrix(evts_1track[,c("Q2QE","qelikeBDTG","1chargedpionBDTG","1neutralpionBDTG","multipionBDTG")])
data_variables_2track <- as.matrix(evts_2track[,c("Q2QE","qelikeBDTG","1chargedpionBDTG","1neutralpionBDTG","multipionBDTG")])
data_variables_3ptrack <- as.matrix(evts_3ptrack[,c("Q2QE","qelikeBDTG","1chargedpionBDTG","1neutralpionBDTG","multipionBDTG")])
data_label_1track <- evts_1track[,"target"]
data_label_2track <- evts_2track[,"target"]
data_label_3ptrack <- evts_3ptrack[,"target"]
data_matrix <- xgb.DMatrix(data = as.matrix(events[,c(14,4:8)]), label = data_label)
# split train data and make xgb.DMatrix
train_data   <- data_variables[train_index,]
train_label  <- data_label[train_index]
train_matrix <- xgb.DMatrix(data = train_data, label = train_label)
# split test data and make xgb.DMatrix
test_data  <- data_variables[-train_index,]
test_label <- data_label[-train_index]
test_matrix <- xgb.DMatrix(data = test_data, label = test_label)

colnames(events2)
```

# XGBoost

```{r, message = F, warning = F, echo = F}
numberOfClasses <- length(unique(events$target))
xgb_params <- list("objective" = "multi:softprob",
                   "eval_metric" = "mlogloss",
                   "num_class" = numberOfClasses)
nround    <- 50 # number of XGBoost rounds
cv.nfold  <- 5

# Fit cv.nfold * cv.nround XGB models and save OOF predictions
cv_model <- xgb.cv(params = xgb_params,
                   data = train_matrix, 
                   nrounds = nround,
                   nfold = cv.nfold,
                   verbose = FALSE,
                   prediction = TRUE)
```

```{r, message = F, warning = F, echo = F}
events %>% group_by(target,Truth) %>% count()
```

```{r, message = F, warning = F, echo = F}
OOF_prediction <- data.frame(cv_model$pred) %>%
  mutate(max_prob = max.col(., ties.method = "last"),
         label = train_label + 1)
head(OOF_prediction)

bst_model <- xgb.train(params = xgb_params,
                       data = train_matrix,
                       nrounds = nround)

# Predict hold-out test set
test_pred <- predict(bst_model, newdata = test_matrix)
test_prediction <- matrix(test_pred, nrow = numberOfClasses,
                          ncol=length(test_pred)/numberOfClasses) %>%
  t() %>%
  data.frame() %>%
  mutate(label = test_label + 1,
         max_prob = max.col(., "last"))
# confusion matrix of test set
cM <- confusionMatrix(factor(test_prediction$max_prob),
                      factor(test_prediction$label),
                      mode = "everything")
colnames(cM$table) <- sort(unique(events$Truth))
rownames(cM$table) <- sort(unique(events$Truth))
rownames(cM$byClass) <- sort(unique(events$Truth))
cM$byClass
cM
```

```{r, message = F, warning = F, echo = F}
# get the feature real names
names <-  colnames(events[,4:8])
# compute feature importance matrix
importance_matrix = xgb.importance(feature_names = names, model = bst_model)
head(importance_matrix)
```
```{r, message = F, warning = F, echo = F}
# plot
gp = xgb.ggplot.importance(importance_matrix)
print(gp) 
```

```{r}
rs = 31411
bchest = 2269
pchest = 14
gchest = 108


(rs*10^3 + bchest*158.4*10^3 + pchest*1.2*10^6 + gchest*3.8*10^6)/10^6 + 136.6
```
```{r}
f = 1036.751
w = 954.6206

(exp(1))
```



