export MINERVA=minervagpvm03.fnal.gov
export DATA=$HOME/data/p4/
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019500_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019501_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019502_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019504_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019505_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019507_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019508_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019509_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019510_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019511_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019512_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019513_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019514_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019515_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019517_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019518_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019519_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019520_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019521_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019523_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019524_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019525_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019530_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019531_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019532_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019533_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019543_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019544_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019545_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019546_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019547_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019548_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019549_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019550_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019551_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019552_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019553_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019554_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019555_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019556_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019557_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019558_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019559_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019560_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019561_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019562_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019564_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019565_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019566_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019567_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019568_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019569_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019570_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019571_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019572_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019573_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019574_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019575_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019576_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019577_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019578_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019579_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019580_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019581_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019582_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019583_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019584_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019585_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019586_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019587_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019588_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019589_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019590_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019591_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019592_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019593_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019594_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019595_Playlist.root $DATA/.
scp $MINERVA:/pnfs/minerva/persistent/DataPreservation/p4/Data/Merged_data_ana_me5A_DualVertex_p4/MasterAnaDev_data_AnaTuple_run00019596_Playlist.root $DATA/.
